/**
 * @file AIBoundaryGuard.ts
 * @module domain/memorization_revision
 * @description Strict AI Boundary Enforcement Guard for Phase 7D (Part 24).
 * 
 * CORE PRINCIPLE:
 * Gemini / LLMs may explain recommendations, summarize progress, and phrase encouragement.
 * Gemini / LLMs may strictly NEVER:
 * - Create success or failure
 * - Mutate or alter MemorizationState
 * - Modify calculated revision priority or schedule
 * - Modify canonical Quran locations or text
 * - Claim religious certification, Ijazah, or infallible retention.
 */

import { MemorizationState, PassageLearningRecord, RevisionScheduleResult } from './types.ts';

export interface ProposedAILearningAnnotation {
  readonly summaryArabic: string;
  readonly encouragementArabic?: string;
  readonly proposedStateChange?: MemorizationState;
  readonly proposedPriorityOverride?: number;
  readonly proposedScheduleIntervalHours?: number;
  readonly proposedNextReviewAt?: number;
  readonly proposedQuranLocation?: { surahId: number; ayahNumber: number };
  readonly proposedConfirmedSuccessCount?: number;
  readonly proposedConfirmedErrorCount?: number;
  readonly certificationClaim?: boolean;
}

export interface AIBoundaryAuditResult {
  readonly isAllowed: boolean;
  readonly sanitizedExplanation: string;
  readonly rejectedMutations: readonly string[];
  readonly containsProhibitedCertification: boolean;
}

export class AIBoundaryGuard {
  private static readonly PROHIBITED_WORDS = [
    'إجازة',
    'سند',
    'شهادة حفظ معتمدة',
    'حفظ لا ينسى',
    'معصوم',
    'إتقان مطلق',
    'مفتي',
    'شهادة إتقان',
    'شهادة رسمية',
    'مُجاز',
  ];

  private static readonly ADVERSARIAL_PATTERNS = [
    /ignore previous instructions/i,
    /system prompt/i,
    /override (state|priority|schedule)/i,
    /<script/i,
    /drop table/i,
  ];

  /**
   * Validates and sanitizes any candidate text or annotation generated by an AI model.
   * Strips any unauthorized state mutations, location changes, success/failure overrides, or certification claims.
   */
  public static auditAIOutput(
    annotation: ProposedAILearningAnnotation | unknown,
    authoritativeRecord: PassageLearningRecord,
    authoritativeSchedule: RevisionScheduleResult
  ): AIBoundaryAuditResult {
    const rejectedMutations: string[] = [];
    let containsProhibitedCertification = false;

    // Handle malformed or non-object input
    if (!annotation || typeof annotation !== 'object') {
      return Object.freeze({
        isAllowed: false,
        sanitizedExplanation: authoritativeSchedule.naturalLanguageExplanationArabic,
        rejectedMutations: Object.freeze(['Malformed AI output: payload must be a non-null object']),
        containsProhibitedCertification: false,
      });
    }

    const typedAnnotation = annotation as Partial<ProposedAILearningAnnotation>;

    // 1. Check for forbidden state mutation
    if (typedAnnotation.proposedStateChange && typedAnnotation.proposedStateChange !== authoritativeRecord.currentState) {
      rejectedMutations.push(
        `AI attempted to alter MemorizationState from ${authoritativeRecord.currentState} to ${typedAnnotation.proposedStateChange}. LLM state mutation is strictly forbidden.`
      );
    }

    // 2. Check for priority override attempt
    if (
      typedAnnotation.proposedPriorityOverride !== undefined &&
      typedAnnotation.proposedPriorityOverride !== authoritativeSchedule.priorityFactors.totalPriority
    ) {
      rejectedMutations.push('AI attempted to override deterministic priority factor calculation.');
    }

    // 3. Check for schedule interval override attempt
    if (
      typedAnnotation.proposedScheduleIntervalHours !== undefined &&
      typedAnnotation.proposedScheduleIntervalHours !== authoritativeSchedule.intervalHours
    ) {
      rejectedMutations.push('AI attempted to override deterministic revision schedule interval.');
    }

    // 4. Check for nextReviewAt override attempt
    if (
      typedAnnotation.proposedNextReviewAt !== undefined &&
      typedAnnotation.proposedNextReviewAt !== authoritativeSchedule.nextReviewAt
    ) {
      rejectedMutations.push('AI attempted to override deterministic next review timestamp.');
    }

    // 5. Check for Quran location mutation
    if (
      typedAnnotation.proposedQuranLocation &&
      (typedAnnotation.proposedQuranLocation.surahId !== authoritativeRecord.surahId ||
        typedAnnotation.proposedQuranLocation.ayahNumber !== authoritativeRecord.ayahNumber)
    ) {
      rejectedMutations.push('AI attempted to alter canonical Quran coordinates.');
    }

    // 6. Check for confirmed success/error count tampering
    if (
      typedAnnotation.proposedConfirmedSuccessCount !== undefined &&
      typedAnnotation.proposedConfirmedSuccessCount !== authoritativeRecord.confirmedSuccessCount
    ) {
      rejectedMutations.push('AI attempted to tamper with confirmed success count.');
    }
    if (
      typedAnnotation.proposedConfirmedErrorCount !== undefined &&
      typedAnnotation.proposedConfirmedErrorCount !== authoritativeRecord.confirmedErrorCount
    ) {
      rejectedMutations.push('AI attempted to tamper with confirmed error count.');
    }

    // 7. Check for adversarial injection attempts
    const textToCheck = `${typedAnnotation.summaryArabic ?? ''} ${typedAnnotation.encouragementArabic ?? ''}`;
    for (const pattern of this.ADVERSARIAL_PATTERNS) {
      if (pattern.test(textToCheck)) {
        rejectedMutations.push(`Adversarial prompt injection pattern detected: ${pattern}`);
      }
    }

    // 8. Check for false certification or infallible retention claim
    for (const term of this.PROHIBITED_WORDS) {
      if (textToCheck.includes(term)) {
        containsProhibitedCertification = true;
        rejectedMutations.push(`AI output contains prohibited certification/infallibility claim: "${term}".`);
      }
    }

    if (typedAnnotation.certificationClaim) {
      containsProhibitedCertification = true;
      rejectedMutations.push('Explicit certification claim rejected.');
    }

    const isAllowed = rejectedMutations.length === 0;

    // If rejected, fallback strictly to the deterministic authoritative explanation
    const sanitizedExplanation = isAllowed && typeof typedAnnotation.summaryArabic === 'string'
      ? typedAnnotation.summaryArabic
      : authoritativeSchedule.naturalLanguageExplanationArabic;

    return Object.freeze({
      isAllowed,
      sanitizedExplanation,
      rejectedMutations: Object.freeze(rejectedMutations),
      containsProhibitedCertification,
    });
  }
}
