/**
 * @file GoldenRecitationSet.ts
 * @module domain/recitation
 * @description Certified Golden Test Set for scientific evaluation, regression,
 * and adversarial validation of the Quranic Zipformer2-CTC phoneme recognizer.
 */

export interface GoldenRecitationEntry {
  id: string;
  reciter: string;
  reciterStyle: 'MURATTAL_STUDIO_MODERATE' | 'MURATTAL_STUDIO_SLOW_EDUCATIONAL' | 'MURATTAL_STUDIO_EMOTIONAL' | 'MURATTAL_STUDIO_BRISK';
  ayahId: string;
  surahNumber: number;
  ayahNumber: number;
  expectedPhonemeSequence: string[];
  audioPath: string;
  audioDurationSeconds: number;
  humanReviewedCorrectness: 'VERIFIED_CORRECT_HAFS' | 'DELIBERATE_ADVERSARIAL_ANOMALY';
  groundTruthError: 'NONE_CORRECT_RECITATION' | 'SUBSTITUTION' | 'DELETION' | 'INSERTION' | 'REPETITION' | 'SILENCE' | 'NOISE' | 'NON_QURANIC_ARABIC';
  reviewSource: string;
  reviewDate: string;
  verificationStatus: 'CERTIFIED_GOLDEN' | 'SYNTHETIC_EVALUATION_ONLY';
  notes: string;
}

export const GOLDEN_RECITATION_SET: GoldenRecitationEntry[] = [
  {
    id: 'GOLDEN-001',
    reciter: 'Sheikh Mishary Rashid Alafasy',
    reciterStyle: 'MURATTAL_STUDIO_MODERATE',
    ayahId: '1:1',
    surahNumber: 1,
    ayahNumber: 1,
    expectedPhonemeSequence: ['بِ', 'س', 'مِ', 'للَ', 'اا', 'هِ', 'ررَ', 'ح', 'مَ', 'اا', 'نِ', 'ررَ', 'حِ', 'ۦۦۦۦ', 'م'],
    audioPath: 'audio_samples/alafasy_001001_16k.wav',
    audioDurationSeconds: 4.88,
    humanReviewedCorrectness: 'VERIFIED_CORRECT_HAFS',
    groundTruthError: 'NONE_CORRECT_RECITATION',
    reviewSource: 'King Fahd Complex / Islamic Network Audio Archive',
    reviewDate: '2026-09-19',
    verificationStatus: 'CERTIFIED_GOLDEN',
    notes: 'Studio high-fidelity recording of Surah Al-Fatihah Ayah 1 (Basmalah) at moderate tempo.',
  },
  {
    id: 'GOLDEN-002',
    reciter: 'Sheikh Mahmoud Khalil Al-Husary',
    reciterStyle: 'MURATTAL_STUDIO_SLOW_EDUCATIONAL',
    ayahId: '1:1',
    surahNumber: 1,
    ayahNumber: 1,
    expectedPhonemeSequence: ['بِ', 'س', 'مِ', 'للَ', 'اا', 'هِ', 'ررَ', 'ح', 'مَ', 'اا', 'نِ', 'ررَ', 'حِ', 'ۦۦۦۦ', 'م'],
    audioPath: 'audio_samples/husary_001001_16k.wav',
    audioDurationSeconds: 6.22,
    humanReviewedCorrectness: 'VERIFIED_CORRECT_HAFS',
    groundTruthError: 'NONE_CORRECT_RECITATION',
    reviewSource: 'Egyptian Radio / Al-Azhar Verified Mus-haf Al-Murattal',
    reviewDate: '2026-09-19',
    verificationStatus: 'CERTIFIED_GOLDEN',
    notes: 'Master educational recording with deliberate, measured pace and classical Tajweed articulation.',
  },
  {
    id: 'GOLDEN-003',
    reciter: 'Sheikh Mishary Rashid Alafasy',
    reciterStyle: 'MURATTAL_STUDIO_MODERATE',
    ayahId: '1:2',
    surahNumber: 1,
    ayahNumber: 2,
    expectedPhonemeSequence: ['ءَ', 'ل', 'حَ', 'م', 'دُ', 'لِ', 'للَ', 'اا', 'هِ', 'رَ', 'ببِ', 'ل', 'عَ', 'اا', 'لَ', 'مِ', 'ۦۦۦۦ', 'ن'],
    audioPath: 'audio_samples/eval/alafasy_001002_16k.wav',
    audioDurationSeconds: 5.56,
    humanReviewedCorrectness: 'VERIFIED_CORRECT_HAFS',
    groundTruthError: 'NONE_CORRECT_RECITATION',
    reviewSource: 'King Fahd Complex / Islamic Network Audio Archive',
    reviewDate: '2026-09-19',
    verificationStatus: 'CERTIFIED_GOLDEN',
    notes: 'Studio recording of Surah Al-Fatihah Ayah 2 at standard tempo.',
  },
  {
    id: 'GOLDEN-004',
    reciter: 'Sheikh Mahmoud Khalil Al-Husary',
    reciterStyle: 'MURATTAL_STUDIO_SLOW_EDUCATIONAL',
    ayahId: '1:2',
    surahNumber: 1,
    ayahNumber: 2,
    expectedPhonemeSequence: ['ءَ', 'ل', 'حَ', 'م', 'دُ', 'لِ', 'للَ', 'اا', 'هِ', 'رَ', 'ببِ', 'ل', 'عَ', 'اا', 'لَ', 'مِ', 'ۦۦۦۦ', 'ن'],
    audioPath: 'audio_samples/eval/husary_001002_16k.wav',
    audioDurationSeconds: 6.30,
    humanReviewedCorrectness: 'VERIFIED_CORRECT_HAFS',
    groundTruthError: 'NONE_CORRECT_RECITATION',
    reviewSource: 'Egyptian Radio / Al-Azhar Verified Mus-haf Al-Murattal',
    reviewDate: '2026-09-19',
    verificationStatus: 'CERTIFIED_GOLDEN',
    notes: 'Master educational recitation of Ayah 1:2 with pristine makharij and pacing.',
  },
  {
    id: 'GOLDEN-005',
    reciter: 'Sheikh Muhammad Siddiq Al-Minshawi',
    reciterStyle: 'MURATTAL_STUDIO_EMOTIONAL',
    ayahId: '1:1',
    surahNumber: 1,
    ayahNumber: 1,
    expectedPhonemeSequence: ['بِ', 'س', 'مِ', 'للَ', 'اا', 'هِ', 'ررَ', 'ح', 'مَ', 'اا', 'نِ', 'ررَ', 'حِ', 'ۦۦۦۦ', 'م'],
    audioPath: 'audio_samples/eval/minshawi_001001_16k.wav',
    audioDurationSeconds: 4.98,
    humanReviewedCorrectness: 'VERIFIED_CORRECT_HAFS',
    groundTruthError: 'NONE_CORRECT_RECITATION',
    reviewSource: 'Egyptian Radio Archive / Islamic Network',
    reviewDate: '2026-09-19',
    verificationStatus: 'CERTIFIED_GOLDEN',
    notes: 'Emotional melodic recitation style with distinct vocal resonances.',
  },
  {
    id: 'GOLDEN-006',
    reciter: 'Sheikh Saad Al-Ghamadi',
    reciterStyle: 'MURATTAL_STUDIO_BRISK',
    ayahId: '1:1',
    surahNumber: 1,
    ayahNumber: 1,
    expectedPhonemeSequence: ['بِ', 'س', 'مِ', 'للَ', 'اا', 'هِ', 'ررَ', 'ح', 'مَ', 'اا', 'نِ', 'ررَ', 'حِ', 'ۦۦۦۦ', 'م'],
    audioPath: 'audio_samples/eval/ghamadi_001001_16k.wav',
    audioDurationSeconds: 3.45,
    humanReviewedCorrectness: 'VERIFIED_CORRECT_HAFS',
    groundTruthError: 'NONE_CORRECT_RECITATION',
    reviewSource: 'Madinah Munawwarah Recitation Archive',
    reviewDate: '2026-09-19',
    verificationStatus: 'CERTIFIED_GOLDEN',
    notes: 'Fast / brisk recitation style testing rapid speech rate robustness.',
  },
  {
    id: 'GOLDEN-007',
    reciter: 'Sheikh Muhammad Siddiq Al-Minshawi',
    reciterStyle: 'MURATTAL_STUDIO_EMOTIONAL',
    ayahId: '1:2',
    surahNumber: 1,
    ayahNumber: 2,
    expectedPhonemeSequence: ['ءَ', 'ل', 'حَ', 'م', 'دُ', 'لِ', 'للَ', 'اا', 'هِ', 'رَ', 'ببِ', 'ل', 'عَ', 'اا', 'لَ', 'مِ', 'ۦۦۦۦ', 'ن'],
    audioPath: 'audio_samples/eval/minshawi_001002_16k.wav',
    audioDurationSeconds: 6.12,
    humanReviewedCorrectness: 'VERIFIED_CORRECT_HAFS',
    groundTruthError: 'NONE_CORRECT_RECITATION',
    reviewSource: 'Egyptian Radio Archive / Islamic Network',
    reviewDate: '2026-09-19',
    verificationStatus: 'CERTIFIED_GOLDEN',
    notes: 'Master emotional recitation of Ayah 1:2 testing melodic cadence and vowel elongations.',
  },
  {
    id: 'GOLDEN-008',
    reciter: 'Sheikh Saad Al-Ghamadi',
    reciterStyle: 'MURATTAL_STUDIO_BRISK',
    ayahId: '1:2',
    surahNumber: 1,
    ayahNumber: 2,
    expectedPhonemeSequence: ['ءَ', 'ل', 'حَ', 'م', 'دُ', 'لِ', 'للَ', 'اا', 'هِ', 'رَ', 'ببِ', 'ل', 'عَ', 'اا', 'لَ', 'مِ', 'ۦۦۦۦ', 'ن'],
    audioPath: 'audio_samples/eval/ghamadi_001002_16k.wav',
    audioDurationSeconds: 3.92,
    humanReviewedCorrectness: 'VERIFIED_CORRECT_HAFS',
    groundTruthError: 'NONE_CORRECT_RECITATION',
    reviewSource: 'Madinah Munawwarah Recitation Archive',
    reviewDate: '2026-09-19',
    verificationStatus: 'CERTIFIED_GOLDEN',
    notes: 'Brisk Murattal recitation of Ayah 1:2 testing rapid speech rate and phonetic stability.',
  },
];

export const SYNTHETIC_ADVERSARIAL_SET: GoldenRecitationEntry[] = [
  {
    id: 'SYNTH-001',
    reciter: 'Synthetic Audio Generator',
    reciterStyle: 'MURATTAL_STUDIO_MODERATE',
    ayahId: '1:1',
    surahNumber: 1,
    ayahNumber: 1,
    expectedPhonemeSequence: [],
    audioPath: 'audio_samples/adversarial/silence_4s_16k.wav',
    audioDurationSeconds: 4.00,
    humanReviewedCorrectness: 'DELIBERATE_ADVERSARIAL_ANOMALY',
    groundTruthError: 'SILENCE',
    reviewSource: 'Synthetic Test Suite',
    reviewDate: '2026-09-19',
    verificationStatus: 'SYNTHETIC_EVALUATION_ONLY',
    notes: '4.0s digital zero silence testing null token emission and REPEAT_REQUESTED gating.',
  },
  {
    id: 'SYNTH-002',
    reciter: 'Synthetic Audio Generator',
    reciterStyle: 'MURATTAL_STUDIO_MODERATE',
    ayahId: '1:1',
    surahNumber: 1,
    ayahNumber: 1,
    expectedPhonemeSequence: [],
    audioPath: 'audio_samples/adversarial/white_noise_4s_16k.wav',
    audioDurationSeconds: 4.00,
    humanReviewedCorrectness: 'DELIBERATE_ADVERSARIAL_ANOMALY',
    groundTruthError: 'NOISE',
    reviewSource: 'Synthetic Test Suite',
    reviewDate: '2026-09-19',
    verificationStatus: 'SYNTHETIC_EVALUATION_ONLY',
    notes: '4.0s Gaussian white noise (-25 dBFS) testing noise hallucination rejection.',
  },
  {
    id: 'SYNTH-003',
    reciter: 'Sheikh Mishary Rashid Alafasy (Spliced)',
    reciterStyle: 'MURATTAL_STUDIO_MODERATE',
    ayahId: '1:1',
    surahNumber: 1,
    ayahNumber: 1,
    expectedPhonemeSequence: ['بِ', 'س', 'مِ', 'للَ', 'اا', 'هِ', 'ررَ', 'ح', 'مَ', 'اا', 'نِ', 'ررَ', 'حِ', 'ۦۦۦۦ', 'م'],
    audioPath: 'audio_samples/adversarial/alafasy_deleted_arrahman_16k.wav',
    audioDurationSeconds: 3.42,
    humanReviewedCorrectness: 'DELIBERATE_ADVERSARIAL_ANOMALY',
    groundTruthError: 'DELETION',
    reviewSource: 'Synthetic Edit of Authentic Recording',
    reviewDate: '2026-09-19',
    verificationStatus: 'SYNTHETIC_EVALUATION_ONLY',
    notes: 'Deliberate splice omitting word Ar-Rahman (5 phonemes deleted).',
  },
  {
    id: 'SYNTH-004',
    reciter: 'Sheikh Mishary Rashid Alafasy (Spliced)',
    reciterStyle: 'MURATTAL_STUDIO_MODERATE',
    ayahId: '1:1',
    surahNumber: 1,
    ayahNumber: 1,
    expectedPhonemeSequence: ['بِ', 'س', 'مِ', 'للَ', 'اا', 'هِ', 'ررَ', 'ح', 'مَ', 'اا', 'نِ', 'ررَ', 'حِ', 'ۦۦۦۦ', 'م'],
    audioPath: 'audio_samples/adversarial/alafasy_repeated_arrahman_16k.wav',
    audioDurationSeconds: 6.34,
    humanReviewedCorrectness: 'DELIBERATE_ADVERSARIAL_ANOMALY',
    groundTruthError: 'REPETITION',
    reviewSource: 'Synthetic Edit of Authentic Recording',
    reviewDate: '2026-09-19',
    verificationStatus: 'SYNTHETIC_EVALUATION_ONLY',
    notes: 'Deliberate duplicate splice repeating Ar-Rahman (5 phonemes inserted).',
  },
  {
    id: 'SYNTH-005',
    reciter: 'Sheikh Mishary Rashid Alafasy (Spliced)',
    reciterStyle: 'MURATTAL_STUDIO_MODERATE',
    ayahId: '1:2',
    surahNumber: 1,
    ayahNumber: 2,
    expectedPhonemeSequence: ['ءَ', 'ل', 'حَ', 'م', 'دُ', 'لِ', 'للَ', 'اا', 'هِ', 'رَ', 'ببِ', 'ل', 'عَ', 'اا', 'لَ', 'مِ', 'ۦۦۦۦ', 'ن'],
    audioPath: 'audio_samples/adversarial/alafasy_substituted_hamd_16k.wav',
    audioDurationSeconds: 5.56,
    humanReviewedCorrectness: 'DELIBERATE_ADVERSARIAL_ANOMALY',
    groundTruthError: 'SUBSTITUTION',
    reviewSource: 'Synthetic Edit of Authentic Recording',
    reviewDate: '2026-09-19',
    verificationStatus: 'SYNTHETIC_EVALUATION_ONLY',
    notes: 'Deliberate cross-ayah splicing replacing initial token with Basmalah fragment.',
  },
];

export const LOCAL_GOLDEN_REGRESSION_SET = {
  classification: 'LOCAL_GOLDEN_REGRESSION_SET' as const,
  purpose: 'Local regression and continuous integration verification of acoustic model execution pipeline.',
  generalPopulationEvidence: false,
  note: 'This dataset is NOT an independent general population test set. It verifies pipeline stability, not general unobserved accuracy.',
  authenticRecordingsCount: GOLDEN_RECITATION_SET.length,
  syntheticAdversarialCount: SYNTHETIC_ADVERSARIAL_SET.length,
  recitersCount: 4,
  reciters: ['Sheikh Mishary Rashid Alafasy', 'Sheikh Mahmoud Khalil Al-Husary', 'Sheikh Muhammad Siddiq Al-Minshawi', 'Sheikh Saad Al-Ghamadi'],
  ayahsCount: 2,
  ayahs: ['1:1', '1:2'],
  totalReferencePhonemes: 132, // (4 * 15) + (4 * 18) = 60 + 72 = 132
  usedDuringDevelopment: true,
  independentOfModelTraining: false, // Reciter recordings may have been included in upstream ~5,400h training corpus
  trainingCorpusOverlapNote: 'Recordings sourced from EveryAyah public repository, which is commonly included in open Quranic ASR training corpora.',
};

