/**
 * @file DeterministicTajweedContextEvaluator.ts
 * @module domain/tajweed
 * @description Phase 5B Deterministic Tajweed Context Evaluator.
 * 
 * MAPS:
 * VERIFIED QURAN CONTEXT + CANONICAL PHONEME CONTEXT + REAL RECITATION EVIDENCE + VERIFIED TAJWEED KNOWLEDGE BASE
 * INTO:
 * DETERMINISTIC RULE EVIDENCE
 * 
 * STRICT ARCHITECTURAL INVARIANTS:
 * 1. Zero LLM inference: Tajweed rules are never guessed, inferred, or generated by an LLM.
 * 2. Strict separation: RULE_APPLICABLE does NOT imply compliance or violation.
 * 3. Inconclusive preservation: Phase 5A uncertainty (low confidence, ambiguity, silence, noise) MUST propagate.
 * 4. Madd duration safety (Section 13): CTC token count / run length is strictly prohibited as a duration proxy.
 * 5. Ghunnah safety (Section 14): Phoneme token identity does not prove nasal resonance acoustic quality.
 * 6. Makhraj safety (Section 15): Zipformer CTC acoustic model cannot prove formant pharyngealization/velarization.
 * 7. Qalqalah safety (Section 16): Acoustic transient release burst analysis is not supported.
 * 8. Non-religious language (Section 20): Zero religious condemnation, no Fiqh rulings (Haram, Sin, Sawab).
 * 9. Cryptographic governance (Section 22): Quran hash, Tajweed KB hash, and Riwayah are strictly verified.
 */

import {
  TajweedRuleEvidence,
  TajweedDecisionStatus,
  TajweedRuleDefinition,
  TajweedCategory,
  QuranLocation,
  CanonicalWordContext,
  CanonicalPhonemeContext,
  RuleEvaluationBlockedError,
  RiwayahNotActivatedError,
} from './types.ts';
import { VerifiedTajweedKnowledgeBase } from './VerifiedTajweedKnowledgeBase.ts';
import { HAFS_OFFICIAL_CERTIFICATE } from '../../infrastructure/quran/VerifiedQuranDataProvider.ts';
import { QuranAlignmentEvidence } from '../recitation/quranAlignmentTypes.ts';

// Deterministic safety thresholds
const MIN_CONFIDENCE = 0.90;
const MIN_MARGIN = 0.80;
const MIN_SNR_DB = 10.0;
const MIN_ALIGNMENT_CONFIDENCE = 0.60;

export class DeterministicTajweedContextEvaluator {
  private readonly kb: VerifiedTajweedKnowledgeBase;

  constructor() {
    this.kb = VerifiedTajweedKnowledgeBase.getInstance();
  }

  /**
   * Evaluates the Tajweed context deterministically for a specific Quranic location and evidence.
   */
  public evaluateTajweedContext(
    quranLocation: QuranLocation,
    canonicalWordContext: CanonicalWordContext,
    canonicalPhonemeContext: CanonicalPhonemeContext,
    recitationEvidence: QuranAlignmentEvidence | any
  ): Readonly<TajweedRuleEvidence> {
    // 1. Governance & Integrity Gate (Section 22)
    this.validateGovernanceAndIntegrity(quranLocation);

    // 2. Identify Applicable Rules from Canonical Uthmani Context
    const applicableRule = this.identifyApplicableRule(canonicalWordContext, canonicalPhonemeContext);

    // 3. Fallback if no specific Tajweed rule is triggered
    if (!applicableRule) {
      return this.createNoRuleEvidence(quranLocation, canonicalWordContext, canonicalPhonemeContext, recitationEvidence);
    }

    // 4. Validate Rule Verification Status in Knowledge Base
    if (!this.kb.isRuleActive(applicableRule.ruleId)) {
      return this.createUnverifiedRuleEvidence(applicableRule, quranLocation, recitationEvidence);
    }

    // 5. Evaluate Acoustic Evidence against Applicable Rule (Sections 10-16)
    return this.evaluateRuleWithEvidence(
      applicableRule,
      quranLocation,
      canonicalWordContext,
      canonicalPhonemeContext,
      recitationEvidence
    );
  }

  /**
   * Evaluates all applicable rules at a given context.
   */
  public evaluateAllRulesAtContext(
    quranLocation: QuranLocation,
    canonicalWordContext: CanonicalWordContext,
    canonicalPhonemeContext: CanonicalPhonemeContext,
    recitationEvidence: QuranAlignmentEvidence | any
  ): ReadonlyArray<TajweedRuleEvidence> {
    const single = this.evaluateTajweedContext(
      quranLocation,
      canonicalWordContext,
      canonicalPhonemeContext,
      recitationEvidence
    );
    return Object.freeze([single]);
  }

  /**
   * Strictly validates cryptographic and Riwayah integrity before permitting evaluation.
   */
  private validateGovernanceAndIntegrity(quranLocation: QuranLocation): void {
    // Check Riwayah: Hafs 'an 'Asim only
    const riwayah = quranLocation.riwayah || 'HAFS_AN_ASIM';
    try {
      this.kb.verifyRiwayah(riwayah);
    } catch (err: any) {
      throw new RuleEvaluationBlockedError(
        `[Phase 5B Governance] Evaluation blocked due to Riwayah mismatch: ${err.message}`,
        'RIWAYAH_NOT_ACTIVATED'
      );
    }

    // Verify Tajweed Knowledge Base SHA-256 integrity
    try {
      this.kb.verifyIntegrity();
    } catch (err: any) {
      throw new RuleEvaluationBlockedError(
        `[Phase 5B Governance] Evaluation blocked due to Tajweed KB integrity mismatch: ${err.message}`,
        'TAJWEED_KB_INTEGRITY_MISMATCH'
      );
    }
  }

  /**
   * Deterministically identifies the classical Tajweed rule triggered by the canonical text context.
   */
  private identifyApplicableRule(
    wordContext: CanonicalWordContext,
    phonemeContext: CanonicalPhonemeContext
  ): TajweedRuleDefinition | null {
    const word = wordContext.currentWordTextUthmani || '';
    const nextWord = wordContext.nextWordTextUthmani || '';
    const phoneme = phonemeContext.currentPhoneme || '';
    const isWaqf = Boolean(wordContext.isEndOfAyahOrPause);

    // Cleaned versions of words without short vowel diacritics for structural consonant matching
    const stripDiacritics = (str: string) => str.replace(/[\u064B-\u065F\u0670]/g, '');
    const cleanWord = stripDiacritics(word);
    const cleanNextWord = stripDiacritics(nextWord);

    // Rule A: Lam Sakinah (Solar / Lunar) - applies to the Lam consonant
    if ((cleanWord.startsWith('ٱل') || cleanWord.startsWith('ال')) && (phoneme === 'l' || (wordContext.isWordInitialConsonant && !['aː', 'uː', 'iː'].includes(phoneme)))) {
      const followingChar = cleanWord.charAt(2);
      
      const solarLetters = ['ط', 'ث', 'ص', 'ر', 'ت', 'ض', 'ذ', 'ن', 'د', 'س', 'ظ', 'ز', 'ش', 'ل'];
      const lunarLetters = ['ء', 'أ', 'إ', 'ب', 'غ', 'ح', 'ج', 'ك', 'و', 'خ', 'ف', 'ع', 'ق', 'ي', 'م', 'ه', 'هـ'];

      if (solarLetters.includes(followingChar)) {
        return this.kb.getRule('lam_shamsiyyah') || null;
      }
      if (lunarLetters.includes(followingChar)) {
        return this.kb.getRule('lam_qamariyyah') || null;
      }
    }

    // Rule B: Ghunnah Mushaddadah (نّ or مّ)
    if (word.includes('نّ') || word.includes('مّ') || word.includes('ن\u0651') || word.includes('م\u0651')) {
      if (phoneme === 'n' || phoneme === 'm') {
        return this.kb.getRule('ghunnah_mushaddadah') || null;
      }
    }

    // Rule C: Qalqalah (قطب جد ساكنة)
    const qalqalahLetters = ['ق', 'ط', 'ب', 'ج', 'د'];
    const qalqalahPhonemes = ['q', 'tˁ', 'b', 'dʒ', 'd'];
    if (qalqalahPhonemes.includes(phoneme)) {
      if (isWaqf && wordContext.isWordFinalConsonant) {
        return this.kb.getRule('qalqalah_kubra') || null;
      }
      for (const qChar of qalqalahLetters) {
        if (word.includes(qChar + 'ْ') || (isWaqf && cleanWord.endsWith(qChar))) {
          return isWaqf ? (this.kb.getRule('qalqalah_kubra') || null) : (this.kb.getRule('qalqalah_sughra') || null);
        }
      }
    }

    // Rule D: Madd rules
    const maddPhonemes = ['aː', 'uː', 'iː'];
    if (maddPhonemes.includes(phoneme)) {
      if (word.includes('ٓ') || word.includes('آ') || word.includes('يٓ') || word.includes('وٓ') || word.includes('\u0653')) {
        // Heavy compulsory madd (followed by shaddah)
        if (word.includes('ّ') || word.includes('\u0651')) {
          return this.kb.getRule('madd_lazim_kalimi_muthaqqal') || null;
        }
        // Connected madd (followed by hamzah in same word)
        if (cleanWord.includes('ء') || cleanWord.includes('أ') || cleanWord.includes('إ') || cleanWord.includes('ئ') || cleanWord.includes('ؤ')) {
          return this.kb.getRule('madd_muttasil') || null;
        }
        // Separated madd (followed by hamzah in next word)
        if (cleanNextWord.startsWith('ء') || cleanNextWord.startsWith('أ') || cleanNextWord.startsWith('إ')) {
          return this.kb.getRule('madd_munfasil') || null;
        }
      }
      // Aridh lis-sukun at waqf
      if (isWaqf) {
        return this.kb.getRule('madd_aridh_lis_sukun') || null;
      }
      // Natural Madd
      return this.kb.getRule('madd_tabii') || null;
    }

    // Rule E: Noon Sakinah & Tanween
    const hasNoonSakinah = word.includes('نْ') || (cleanWord.endsWith('ن') && !word.endsWith('نَ') && !word.endsWith('نِ') && !word.endsWith('نُ'));
    const hasTanween = word.includes('ً') || word.includes('ٍ') || word.includes('ٌ');

    if ((hasNoonSakinah || hasTanween) && (phoneme === 'n' || wordContext.isWordFinalConsonant)) {
      let nextChar = '';
      if (wordContext.isWordFinalConsonant || cleanWord.endsWith('ن') || hasTanween) {
        nextChar = cleanNextWord ? cleanNextWord.charAt(0) : '';
      } else {
        const noonIdx = cleanWord.indexOf('ن');
        if (noonIdx !== -1 && noonIdx < cleanWord.length - 1) {
          nextChar = cleanWord.charAt(noonIdx + 1);
        } else if (cleanNextWord) {
          nextChar = cleanNextWord.charAt(0);
        }
      }

      if (['ء', 'أ', 'إ', 'ه', 'هـ', 'ع', 'ح', 'غ', 'خ'].includes(nextChar)) {
        return this.kb.getRule('noon_izhar_halqi') || null;
      }
      if (['ي', 'ن', 'م', 'و'].includes(nextChar)) {
        return this.kb.getRule('noon_idgham_bi_ghunnah') || null;
      }
      if (['ل', 'ر'].includes(nextChar)) {
        return this.kb.getRule('noon_idgham_bila_ghunnah') || null;
      }
      if (nextChar === 'ب') {
        return this.kb.getRule('noon_iqlab') || null;
      }
      if (['ص', 'ذ', 'ث', 'ك', 'ج', 'ش', 'ق', 'س', 'د', 'ط', 'ز', 'ف', 'ت', 'ض', 'ظ'].includes(nextChar)) {
        return this.kb.getRule('noon_ikhfa_haqiqi') || null;
      }
    }

    // Rule F: Meem Sakinah
    const hasMeemSakinah = word.includes('مْ') || (cleanWord.endsWith('م') && !word.endsWith('مَ') && !word.endsWith('مِ') && !word.endsWith('مُ'));
    if (hasMeemSakinah && (phoneme === 'm' || wordContext.isWordFinalConsonant)) {
      let nextChar = '';
      if (wordContext.isWordFinalConsonant || cleanWord.endsWith('م')) {
        nextChar = cleanNextWord ? cleanNextWord.charAt(0) : '';
      } else {
        const meemIdx = cleanWord.indexOf('م');
        if (meemIdx !== -1 && meemIdx < cleanWord.length - 1) {
          nextChar = cleanWord.charAt(meemIdx + 1);
        } else if (cleanNextWord) {
          nextChar = cleanNextWord.charAt(0);
        }
      }

      if (nextChar === 'ب') {
        return this.kb.getRule('meem_ikhfa_shafawi') || null;
      }
      if (nextChar === 'م') {
        return this.kb.getRule('meem_idgham_shafawi') || null;
      }
      if (nextChar) {
        return this.kb.getRule('meem_izhar_shafawi') || null;
      }
    }

    // Rule G: Tafkheem Isti'la
    const istiLaPhonemes = ['x', 'sˁ', 'dˁ', 'ɣ', 'tˁ', 'q', 'ðˁ'];
    if (istiLaPhonemes.includes(phoneme)) {
      return this.kb.getRule('tafkheem_isti_la') || null;
    }

    return null;
  }

  /**
   * Evaluates the applicable rule against the real acoustic/phonemic evidence.
   */
  private evaluateRuleWithEvidence(
    rule: TajweedRuleDefinition,
    quranLocation: QuranLocation,
    canonicalWordContext: CanonicalWordContext,
    canonicalPhonemeContext: CanonicalPhonemeContext,
    evidence: QuranAlignmentEvidence | any
  ): Readonly<TajweedRuleEvidence> {
    const evidenceId = evidence.evidenceId || `ev-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`;
    const acousticConf = Number(evidence.acousticConfidence ?? 0);
    const alignmentConf = Number(evidence.alignmentConfidence ?? 1.0);
    const marginPeak = Number(evidence.marginPeak ?? 1.0);
    const snrDb = Number(evidence.snrDb ?? 20.0);
    const isAmbiguous = Boolean(evidence.isAmbiguous);
    const evidenceStatus = String(evidence.evidenceStatus || evidence.classification || '');
    const observedToken = String(evidence.observedToken || evidence.observedPhoneme || '');
    const canonicalPhoneme = canonicalPhonemeContext.currentPhoneme;

    const startTime = typeof evidence.startTime === 'number' ? evidence.startTime : undefined;
    const endTime = typeof evidence.endTime === 'number' ? evidence.endTime : undefined;

    let decisionStatus: TajweedDecisionStatus = 'RULE_APPLICABLE';
    let observedEvidenceDesc = '';
    let decisionPath = '';

    // =========================================================================
    // SAFETY GATE 1: Phase 5A Inconclusive / Ambiguity Propagation (Section 10)
    // =========================================================================
    if (
      evidenceStatus === 'INCONCLUSIVE' ||
      evidence.errorType === 'INCONCLUSIVE' ||
      evidence.errorType === 'UNCERTAIN' ||
      isAmbiguous
    ) {
      decisionStatus = 'INCONCLUSIVE';
      observedEvidenceDesc = 'Acoustic evidence is inconclusive or ambiguous from Phase 5A alignment (ERR-ALIGN-003).';
      decisionPath = 'INCONCLUSIVE_PROPAGATED_FROM_PHASE5A';

      return this.buildEvidenceResult({
        evidenceId,
        quranLocation,
        rule,
        decisionStatus,
        expectedCondition: rule.definitionArabic,
        observedEvidence: observedEvidenceDesc,
        acousticConfidence: acousticConf,
        alignmentConfidence: alignmentConf,
        applicabilityConfidence: 1.0,
        startTime,
        endTime,
        decisionPath,
        explanationArabic: 'الأدلة الصوتية غير كافية لإصدار حكم موثوق، يُرجى إعادة التلاوة.',
        explanationEnglish: 'Acoustic evidence is insufficient for a reliable classification. Please repeat the recitation.',
      });
    }

    // =========================================================================
    // SAFETY GATE 2: Confidence, Peak Margin & SNR Safety Gates (Section 11)
    // =========================================================================
    if (
      acousticConf < MIN_CONFIDENCE ||
      marginPeak < MIN_MARGIN ||
      snrDb < MIN_SNR_DB ||
      alignmentConf < MIN_ALIGNMENT_CONFIDENCE
    ) {
      decisionStatus = 'INCONCLUSIVE';
      observedEvidenceDesc = `Acoustic confidence (${acousticConf.toFixed(2)}), margin peak (${marginPeak.toFixed(2)}), or SNR (${snrDb.toFixed(1)} dB) fell below required safety thresholds.`;
      decisionPath = 'INCONCLUSIVE_LOW_ACOUSTIC_METRICS';

      return this.buildEvidenceResult({
        evidenceId,
        quranLocation,
        rule,
        decisionStatus,
        expectedCondition: rule.definitionArabic,
        observedEvidence: observedEvidenceDesc,
        acousticConfidence: acousticConf,
        alignmentConfidence: alignmentConf,
        applicabilityConfidence: 1.0,
        startTime,
        endTime,
        decisionPath,
        explanationArabic: 'الأدلة الصوتية غير كافية لإصدار حكم موثوق، يُرجى إعادة التلاوة.',
        explanationEnglish: 'Acoustic evidence is insufficient for a reliable classification. Please repeat the recitation.',
      });
    }

    // =========================================================================
    // SAFETY GATE 3: Madd Timing Resolution Safety (Section 13)
    // Mandate: CTC token count or run length is strictly prohibited as Madd duration proxy.
    // =========================================================================
    if (rule.category === TajweedCategory.MADD) {
      decisionStatus = 'INCONCLUSIVE';
      observedEvidenceDesc = 'MADD_ACOUSTIC_INCONCLUSIVE: Precise harakah duration measurement requires calibrated sub-frame temporal baseline; CTC token run-length classification is prohibited (ERR-TAJ-001).';
      decisionPath = 'INCONCLUSIVE_MADD_DURATION_RESOLUTION_UNAVAILABLE';

      return this.buildEvidenceResult({
        evidenceId,
        quranLocation,
        rule,
        decisionStatus,
        expectedCondition: `مراعاة زمن المد بمقدار ${rule.harakahDuration?.standardCounts || 2} حركات`,
        observedEvidence: observedEvidenceDesc,
        acousticConfidence: acousticConf,
        alignmentConfidence: alignmentConf,
        applicabilityConfidence: 1.0,
        startTime,
        endTime,
        decisionPath,
        explanationArabic: 'الحكم منطبق نظرياً بناءً على الرسم العثماني المعتمد، وقياس زمن المد الصوتي غير كافٍ آلياً حالياً.',
        explanationEnglish: 'Rule is applicable according to the certified Uthmani text context, but acoustic Madd duration measurement is inconclusive.',
      });
    }

    // =========================================================================
    // SAFETY GATE 4: Ghunnah Nasal Resonance Safety (Section 14)
    // Mandate: Phoneme recognition alone cannot prove nasal resonance quality.
    // =========================================================================
    if (rule.requiresGhunnah || rule.category === TajweedCategory.GHUNNAH) {
      decisionStatus = 'INCONCLUSIVE';
      observedEvidenceDesc = 'GHUNNAH_ACOUSTIC_INCONCLUSIVE: Nasal resonance acoustic quality requires specialized acoustic feature extraction not present in phoneme recognizer alone (ERR-TAJ-002).';
      decisionPath = 'INCONCLUSIVE_GHUNNAH_ACOUSTIC_QUALITY_UNAVAILABLE';

      return this.buildEvidenceResult({
        evidenceId,
        quranLocation,
        rule,
        decisionStatus,
        expectedCondition: 'جريان صوت الغنة بمقدار حركتين من الخيشوم',
        observedEvidence: observedEvidenceDesc,
        acousticConfidence: acousticConf,
        alignmentConfidence: alignmentConf,
        applicabilityConfidence: 1.0,
        startTime,
        endTime,
        decisionPath,
        explanationArabic: 'الحكم منطبق نظرياً بناءً على الرسم العثماني المعتمد، والأدلة الصوتية لرنين الغنة غير كافية.',
        explanationEnglish: 'Rule is applicable according to the certified Uthmani text context, but nasal resonance acoustic evidence is inconclusive.',
      });
    }

    // =========================================================================
    // SAFETY GATE 5: Makhraj Articulation Safety (Section 15)
    // Mandate: Zipformer acoustic model cannot prove formant-level velarization.
    // =========================================================================
    if (rule.category === TajweedCategory.TAFKHEEM_TARQEEQ) {
      decisionStatus = 'INCONCLUSIVE';
      observedEvidenceDesc = 'ARTICULATION_ACOUSTIC_INCONCLUSIVE: Formant-based pharyngealization/velarization verification is not supported by general acoustic model alone (ERR-TAJ-003).';
      decisionPath = 'INCONCLUSIVE_ARTICULATION_ACOUSTIC_UNAVAILABLE';

      return this.buildEvidenceResult({
        evidenceId,
        quranLocation,
        rule,
        decisionStatus,
        expectedCondition: 'تفخيم الحرف وتسمينه في المخرج ليمتلئ الفم بصداه',
        observedEvidence: observedEvidenceDesc,
        acousticConfidence: acousticConf,
        alignmentConfidence: alignmentConf,
        applicabilityConfidence: 1.0,
        startTime,
        endTime,
        decisionPath,
        explanationArabic: 'الحكم منطبق نظرياً بناءً على الرسم العثماني المعتمد، والأدلة الصوتية لصفة الاستعلاء غير كافية.',
        explanationEnglish: 'Rule is applicable according to the certified Uthmani text context, but formant articulation evidence is inconclusive.',
      });
    }

    // =========================================================================
    // SAFETY GATE 6: Qalqalah Transient Release Safety (Section 16)
    // Mandate: Transient release burst analysis is not supported.
    // =========================================================================
    if (rule.category === TajweedCategory.QALQALAH) {
      decisionStatus = 'INCONCLUSIVE';
      observedEvidenceDesc = 'QALQALAH_ACOUSTIC_INCONCLUSIVE: Acoustic transient release analysis is not supported by current frame-level CTC model (ERR-TAJ-004).';
      decisionPath = 'INCONCLUSIVE_QALQALAH_TRANSIENT_UNAVAILABLE';

      return this.buildEvidenceResult({
        evidenceId,
        quranLocation,
        rule,
        decisionStatus,
        expectedCondition: 'اضطراب المخرج عند النطق بالحرف الساكن لإحداث نبرة ارتدادية',
        observedEvidence: observedEvidenceDesc,
        acousticConfidence: acousticConf,
        alignmentConfidence: alignmentConf,
        applicabilityConfidence: 1.0,
        startTime,
        endTime,
        decisionPath,
        explanationArabic: 'الحكم منطبق نظرياً بناءً على الرسم العثماني المعتمد، والأدلة الصوتية لارتداد القلقلة غير كافية.',
        explanationEnglish: 'Rule is applicable according to the certified Uthmani text context, but acoustic transient release evidence is inconclusive.',
      });
    }

    // =========================================================================
    // EVALUATION STEP 7: Phonetic Match / Discrepancy Evaluation (Section 12)
    // Evaluates rules where phonetic identity is determinative (e.g. Lam Qamariyyah, Lam Shamsiyyah, Izhar).
    // =========================================================================
    let isPhoneticMatch = false;

    if (rule.ruleId === 'lam_qamariyyah') {
      // Expects 'l'
      isPhoneticMatch = observedToken === 'l';
    } else if (rule.ruleId === 'lam_shamsiyyah') {
      // Expects lam assimilated into next consonant (not 'l')
      isPhoneticMatch = observedToken !== 'l';
    } else if (rule.ruleId === 'noon_izhar_halqi') {
      // Expects clear 'n'
      isPhoneticMatch = observedToken === 'n';
    } else if (rule.ruleId === 'noon_idgham_bila_ghunnah') {
      // Expects assimilation into 'l' or 'r'
      isPhoneticMatch = observedToken === 'l' || observedToken === 'r';
    } else if (rule.ruleId === 'meem_izhar_shafawi') {
      // Expects clear 'm'
      isPhoneticMatch = observedToken === 'm';
    } else {
      // General match check
      isPhoneticMatch = observedToken === canonicalPhoneme;
    }

    if (isPhoneticMatch) {
      decisionStatus = 'SUPPORTED';
      observedEvidenceDesc = `Observed phonetic token '${observedToken}' matches expected canonical rule condition.`;
      decisionPath = 'EVALUATION_SUPPORTED_EXACT_PHONETIC_MATCH';

      return this.buildEvidenceResult({
        evidenceId,
        quranLocation,
        rule,
        decisionStatus,
        expectedCondition: rule.definitionArabic,
        observedEvidence: observedEvidenceDesc,
        acousticConfidence: acousticConf,
        alignmentConfidence: alignmentConf,
        applicabilityConfidence: 1.0,
        startTime,
        endTime,
        decisionPath,
        explanationArabic: 'تم رصد النطق الصوتي المطابق للوجه المتلو.',
        explanationEnglish: 'Observed phonetic evidence is consistent with expected recitation.',
      });
    } else {
      decisionStatus = 'NOT_SUPPORTED';
      observedEvidenceDesc = `Observed phonetic token '${observedToken}' differs from expected canonical rule condition (expected '${canonicalPhoneme}').`;
      decisionPath = 'EVALUATION_NOT_SUPPORTED_PHONETIC_DISCREPANCY';

      return this.buildEvidenceResult({
        evidenceId,
        quranLocation,
        rule,
        decisionStatus,
        expectedCondition: rule.definitionArabic,
        observedEvidence: observedEvidenceDesc,
        acousticConfidence: acousticConf,
        alignmentConfidence: alignmentConf,
        applicabilityConfidence: 1.0,
        startTime,
        endTime,
        decisionPath,
        explanationArabic: 'يختلف الدليل الصوتي المرصود عن الوجه القرآني المتوقع.',
        explanationEnglish: 'Observed phonetic evidence differs from the expected canonical condition.',
      });
    }
  }

  /**
   * Fallback for contexts where no specific Tajweed rule is triggered.
   */
  private createNoRuleEvidence(
    quranLocation: QuranLocation,
    wordContext: CanonicalWordContext,
    phonemeContext: CanonicalPhonemeContext,
    evidence: any
  ): Readonly<TajweedRuleEvidence> {
    const evidenceId = evidence.evidenceId || `ev-norule-${Date.now()}`;
    const acousticConf = Number(evidence.acousticConfidence ?? 0);
    const alignmentConf = Number(evidence.alignmentConfidence ?? 1.0);

    return Object.freeze({
      evidenceId,
      ayahId: quranLocation.ayahId,
      wordIndex: quranLocation.wordIndex,
      phonemeIndex: quranLocation.phonemeIndex,
      ruleId: 'NO_SPECIFIC_TAJWEED_RULE',
      ruleName: 'Standard Canonical Articulation',
      arabicRuleName: 'نطق أصلي قياسي',
      ruleStatus: 'NOT_ACTIVE',
      expectedCondition: 'تحقيق المخرج والحركة القياسية وفق الرسم العثماني',
      observedEvidence: `Observed token '${evidence.observedToken || evidence.observedPhoneme || phonemeContext.currentPhoneme}'`,
      acousticConfidence: acousticConf,
      alignmentConfidence: alignmentConf,
      applicabilityConfidence: 0.0,
      startTime: evidence.startTime,
      endTime: evidence.endTime,
      sourceReference: 'الأصل في الكلمات القرآنية النطق بالتحقيق وفق الرواية',
      knowledgeBaseVersion: this.kb.getCertificate().kbVersion,
      verificationStatus: 'VERIFIED',
      decisionStatus: 'NOT_VERIFIED',
      provenance: {
        quranDatasetVersion: HAFS_OFFICIAL_CERTIFICATE.editionVersion,
        quranDatasetHash: HAFS_OFFICIAL_CERTIFICATE.checksumSha256,
        tajweedKbVersion: this.kb.getCertificate().kbVersion,
        tajweedKbHash: this.kb.getCertificate().checksumSha256,
        ruleId: 'NO_SPECIFIC_TAJWEED_RULE',
        sourceReference: 'الرسم العثماني المعتمد',
        sourceVerificationStatus: 'VERIFIED' as const,
        evidenceId,
        modelVersion: 'zipformer2-ctc-ar-v1',
        alignmentVersion: 'phase5a-alignment-v1',
        preprocessingVersion: 'kaldi-fbank-80-v1',
        timestamp: new Date().toISOString(),
        decisionPath: 'NO_SPECIFIC_TAJWEED_RULE_APPLICABLE',
      },
      userFacingExplanationArabic: 'لا يوجد حكم تجويدي فرعي خاص في هذا الموضع، والأصل هو النطق القياسي.',
      userFacingExplanationEnglish: 'No specific specialized Tajweed rule is triggered at this position; standard articulation applies.',
    });
  }

  /**
   * Helper to produce evidence for an unverified rule attempt.
   */
  private createUnverifiedRuleEvidence(
    rule: TajweedRuleDefinition,
    quranLocation: QuranLocation,
    evidence: any
  ): Readonly<TajweedRuleEvidence> {
    const evidenceId = evidence.evidenceId || `ev-unverified-${Date.now()}`;
    return Object.freeze({
      evidenceId,
      ayahId: quranLocation.ayahId,
      wordIndex: quranLocation.wordIndex,
      phonemeIndex: quranLocation.phonemeIndex,
      ruleId: rule.ruleId,
      ruleName: rule.englishName,
      arabicRuleName: rule.arabicName,
      ruleStatus: 'NOT_ACTIVE',
      expectedCondition: 'UNVERIFIED_RULE_SOURCE',
      observedEvidence: 'Rule source is unverified or blocked by knowledge base governance.',
      acousticConfidence: 0.0,
      alignmentConfidence: 0.0,
      applicabilityConfidence: 0.0,
      startTime: evidence.startTime,
      endTime: evidence.endTime,
      sourceReference: rule.sourceReference || 'UNKNOWN_UNVERIFIED_SOURCE',
      knowledgeBaseVersion: this.kb.getCertificate().kbVersion,
      verificationStatus: 'UNVERIFIED',
      decisionStatus: 'NOT_VERIFIED',
      provenance: {
        quranDatasetVersion: HAFS_OFFICIAL_CERTIFICATE.editionVersion,
        quranDatasetHash: HAFS_OFFICIAL_CERTIFICATE.checksumSha256,
        tajweedKbVersion: this.kb.getCertificate().kbVersion,
        tajweedKbHash: this.kb.getCertificate().checksumSha256,
        ruleId: rule.ruleId,
        sourceReference: 'UNVERIFIED',
        sourceVerificationStatus: 'UNVERIFIED' as const,
        evidenceId,
        modelVersion: 'zipformer2-ctc-ar-v1',
        alignmentVersion: 'phase5a-alignment-v1',
        preprocessingVersion: 'kaldi-fbank-80-v1',
        timestamp: new Date().toISOString(),
        decisionPath: 'RULE_UNVERIFIED_REJECTED',
      },
      userFacingExplanationArabic: 'هذا الحكم غير معتمد في قاعدة المعرفة المحققة.',
      userFacingExplanationEnglish: 'This rule is not verified or active in the certified Tajweed knowledge base.',
    });
  }

  /**
   * Helper to construct and deeply freeze the TajweedRuleEvidence object.
   */
  private buildEvidenceResult(params: {
    evidenceId: string;
    quranLocation: QuranLocation;
    rule: TajweedRuleDefinition;
    decisionStatus: TajweedDecisionStatus;
    expectedCondition: string;
    observedEvidence: string;
    acousticConfidence: number;
    alignmentConfidence: number;
    applicabilityConfidence: number;
    startTime?: number;
    endTime?: number;
    decisionPath: string;
    explanationArabic: string;
    explanationEnglish: string;
  }): Readonly<TajweedRuleEvidence> {
    const cert = this.kb.getCertificate();

    const result: TajweedRuleEvidence = {
      evidenceId: params.evidenceId,
      ayahId: params.quranLocation.ayahId,
      wordIndex: params.quranLocation.wordIndex,
      phonemeIndex: params.quranLocation.phonemeIndex,
      ruleId: params.rule.ruleId,
      ruleName: params.rule.canonicalRuleName || params.rule.englishName,
      arabicRuleName: params.rule.arabicRuleName || params.rule.arabicName,
      ruleStatus: params.rule.ruleStatus,
      expectedCondition: params.expectedCondition,
      observedEvidence: params.observedEvidence,
      acousticConfidence: params.acousticConfidence,
      alignmentConfidence: params.alignmentConfidence,
      applicabilityConfidence: params.applicabilityConfidence,
      startTime: params.startTime,
      endTime: params.endTime,
      sourceReference: params.rule.sourceReference || '',
      knowledgeBaseVersion: cert.kbVersion,
      verificationStatus: params.rule.verificationStatus,
      decisionStatus: params.decisionStatus,
      provenance: {
        quranDatasetVersion: HAFS_OFFICIAL_CERTIFICATE.editionVersion,
        quranDatasetHash: HAFS_OFFICIAL_CERTIFICATE.checksumSha256,
        tajweedKbVersion: cert.kbVersion,
        tajweedKbHash: cert.checksumSha256,
        ruleId: params.rule.ruleId,
        sourceReference: params.rule.sourceReference || '',
        sourceVerificationStatus: params.rule.verificationStatus,
        evidenceId: params.evidenceId,
        modelVersion: 'zipformer2-ctc-ar-v1',
        alignmentVersion: 'phase5a-alignment-v1',
        preprocessingVersion: 'kaldi-fbank-80-v1',
        timestamp: new Date().toISOString(),
        decisionPath: params.decisionPath,
      },
      userFacingExplanationArabic: params.explanationArabic,
      userFacingExplanationEnglish: params.explanationEnglish,
    };

    return Object.freeze(result);
  }
}
