/**
 * @file rulesCatalog.ts
 * @module domain/tajweed
 * @description Canonical Deterministic Tajweed Knowledge Base Catalog.
 * Fully grounded in classical authorities: Tuhfat al-Atfal (Al-Jamzuri) and Al-Muqaddimah al-Jazariyyah (Ibn al-Jazari).
 * Absolute determinism - zero LLM speculation.
 * 
 * Each rule satisfies the Phase 5B Domain Contract:
 * - ruleId
 * - canonical rule name (englishName / canonicalRuleName)
 * - Arabic rule name (arabicName / arabicRuleName)
 * - definition (definitionArabic / definition)
 * - triggering condition (triggeringCondition)
 * - affected letters/phonemes (affectedLetters / affectedPhonemes)
 * - positional/context requirements (positionalRequirements)
 * - exceptions (exceptions)
 * - Quranic applicability (quranicApplicability)
 * - source/reference (sourceReference / classicalCitation)
 * - verification status (verificationStatus = 'VERIFIED')
 * - knowledge-base version (knowledgeBaseVersion = 'v1.0.0-hafs.tajweed.verified')
 * - evidence provenance (evidenceProvenance)
 * - rule status (ruleStatus = 'ACTIVE')
 */

import {
  TajweedCategory,
  MaddSubtype,
  QalqalahDegree,
  TajweedRuleDefinition,
} from './types.ts';

export const TAJWEED_KB_VERSION = 'v1.0.0-hafs.tajweed.verified';

export const CANONICAL_TAJWEED_RULES: Record<string, TajweedRuleDefinition> = {
  // 1. أحكام النون الساكنة والتنوين
  'noon_izhar_halqi': {
    ruleId: 'noon_izhar_halqi',
    category: TajweedCategory.NOON_SAKINAH_TANWEEN,
    arabicName: 'إظهار حلقي',
    englishName: 'Izhar Halqi (Throat Manifestation)',
    canonicalRuleName: 'Izhar Halqi (Throat Manifestation)',
    arabicRuleName: 'إظهار حلقي',
    definition: 'إخراج النون الساكنة أو التنوين من مخرجها بغير غنة ظاهرة إذا جاء بعدها أحد حروف الحلق الستة.',
    definitionArabic: 'إخراج النون الساكنة أو التنوين من مخرجها بغير غنة ظاهرة إذا جاء بعدها أحد حروف الحلق الستة.',
    lettersArabic: ['ء', 'هـ', 'ع', 'ح', 'غ', 'خ'],
    affectedLetters: ['ء', 'هـ', 'ع', 'ح', 'غ', 'خ'],
    affectedPhonemes: ['n', 'ʔ', 'h', 'ʕ', 'ħ', 'ɣ', 'x'],
    triggeringCondition: {
      description: 'نون ساكنة أو تنوين متبوع بأحد حروف الحلق الستة (ء، هـ، ع، ح، غ، خ)',
      previousContext: [],
      currentContext: ['نْ', 'ً', 'ٍ', 'ٌ'],
      nextContext: ['ء', 'أ', 'إ', 'ه', 'هـ', 'ع', 'ح', 'غ', 'خ'],
    },
    positionalRequirements: 'يقع في كلمة واحدة (مثل: أَنْعَمْتَ، يَنْأَوْنَ) أو في كلمتين (مثل: مَنْ ءَامَنَ، مِنْ حَكِيمٍ)',
    exceptions: ['لا استثناء في رواية حفص عن عاصم من طريق الشاطبية'],
    quranicApplicability: 'سائر مواضع النون الساكنة والتنوين قبل حروف الحلق في القرآن الكريم',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام النون الساكنة والتنوين (الأبيات 6-8)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'متن تحفة الأطفال بشرح الضباع وعلي الضباع وعطية نصر',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام النون الساكنة والتنوين',
      verseArabic: 'فالأول الإظهار قبل أحرفِ ** للحلق ست رُتّبت فلتعرفِ: همزٌ فهاءٌ ثم عينٌ حاءُ ** مهملتان ثم غينٌ خاءُ',
    },
    pedagogicalTipArabic: 'أظهر النون بنطق واضح وسريع دون سكت ودون تمطيط أو غنة زائدة.',
    commonMistakeArabic: 'القلقلة عند النطق بالنون الساكنة، أو إحداث غنة زائدة فيها.',
    isMandatoryInHafs: true,
  },

  'noon_idgham_bi_ghunnah': {
    ruleId: 'noon_idgham_bi_ghunnah',
    category: TajweedCategory.NOON_SAKINAH_TANWEEN,
    arabicName: 'إدغام بغنة (ناقص)',
    englishName: 'Idgham with Ghunnah',
    canonicalRuleName: 'Idgham with Ghunnah',
    arabicRuleName: 'إدغام بغنة (ناقص)',
    definition: 'دمج النون الساكنة أو التنوين في الحرف التالي مع بقاء صفة الغنة بمقدار حركتين في حروف (ينمو).',
    definitionArabic: 'دمج النون الساكنة أو التنوين في الحرف التالي مع بقاء صفة الغنة بمقدار حركتين في حروف (ينمو).',
    lettersArabic: ['ي', 'ن', 'م', 'و'],
    affectedLetters: ['ي', 'ن', 'م', 'و'],
    affectedPhonemes: ['n', 'j', 'm', 'w'],
    triggeringCondition: {
      description: 'نون ساكنة في آخر الكلمة أو تنوين متبوع بأحد حروف (ي، ن، م، و) في أول الكلمة التالية',
      previousContext: [],
      currentContext: ['نْ', 'ً', 'ٍ', 'ٌ'],
      nextContext: ['ي', 'ن', 'م', 'و'],
    },
    positionalRequirements: 'لا يقع إلا بين كلمتين منفصلتين. إذا وقع في كلمة واحدة وجب الإظهار المطلق.',
    exceptions: ['الإظهار المطلق في أربع كلمات فقط في القرآن: دُنْيَا، بُنْيَان، قِنْوَان، صِنْوَان، ون وح والقلم عند الوصل على وجه السكت لحفص'],
    quranicApplicability: 'سائر مواضع النون والتنوين قبل حروف ينمو المنفصلة',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام النون الساكنة والتنوين (الأبيات 9-11)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'متن تحفة الأطفال وشروح علماء القراءات المعتمدة',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: true,
    ghunnahDurationHarakah: 2,
    harakahDuration: {
      minCounts: 2,
      maxCounts: 2,
      standardCounts: 2,
      unitArabic: 'حركتان',
    },
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام النون الساكنة والتنوين',
      verseArabic: 'والثانِ إدغامٌ بستةٍ أتت ** في يرملون عندهم قد ثبتتِ / لكنها قسمانِ قسمٌ يُدغما ** فيه بغنةٍ بينمو عُلما',
    },
    pedagogicalTipArabic: 'وجّه الصوت إلى الخيشوم مع إدماج النون في الحرف التالي بمقدار حركتين بسلاسة.',
    commonMistakeArabic: 'بتر الغنة وجعل الإدغام محضاً بلا غنة، أو المبالغة في زيادة زمن الغنة عن حركتين.',
    isMandatoryInHafs: true,
  },

  'noon_idgham_bila_ghunnah': {
    ruleId: 'noon_idgham_bila_ghunnah',
    category: TajweedCategory.NOON_SAKINAH_TANWEEN,
    arabicName: 'إدغام بغير غنة (كامل)',
    englishName: 'Idgham without Ghunnah',
    canonicalRuleName: 'Idgham without Ghunnah',
    arabicRuleName: 'إدغام بغير غنة (كامل)',
    definition: 'دمج النون الساكنة أو التنوين في اللام أو الراء دمجاً كاملاً يذهب معه ذات الحرف وصفته دون غنة.',
    definitionArabic: 'دمج النون الساكنة أو التنوين في اللام أو الراء دمجاً كاملاً يذهب معه ذات الحرف وصفته دون غنة.',
    lettersArabic: ['ل', 'ر'],
    affectedLetters: ['ل', 'ر'],
    affectedPhonemes: ['n', 'l', 'r'],
    triggeringCondition: {
      description: 'نون ساكنة أو تنوين متبوع بحرف اللام أو الراء في الكلمة التالية',
      previousContext: [],
      currentContext: ['نْ', 'ً', 'ٍ', 'ٌ'],
      nextContext: ['ل', 'ر'],
    },
    positionalRequirements: 'لا يكون إلا من كلمتين (مثل: مَن رَّبِّهِمْ، هُدًى لِّلْمُتَّقِينَ)',
    exceptions: ['موضع: (وَقِيلَ مَنْۜ رَاقٍ) في القيامة بسبب السكت الواجب لحفص من طريق الشاطبية'],
    quranicApplicability: 'سائر مواضع النون والتنوين قبل اللام والراء عدا موضع السكت بالقيامة',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام النون الساكنة والتنوين (البيت 13)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'متن تحفة الأطفال والشاطبية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام النون الساكنة والتنوين',
      verseArabic: 'والثانِ إدغامٌ بغير غنةِ ** في اللام والرا ثم كرّرنّهِ',
    },
    pedagogicalTipArabic: 'أدغم النون إدغاماً تاماً في اللام والراء كأنهما حرف مشدد، مع الحذر من تكرير الراء المفرط.',
    commonMistakeArabic: 'ترك أثر للغنة في اللام والراء، أو تكرير الراء تكراراً فاحشاً.',
    isMandatoryInHafs: true,
  },

  'noon_iqlab': {
    ruleId: 'noon_iqlab',
    category: TajweedCategory.NOON_SAKINAH_TANWEEN,
    arabicName: 'إقلاب (قلب النون ميماً مخفاة)',
    englishName: 'Iqlab (Conversion to Meem)',
    canonicalRuleName: 'Iqlab (Conversion to Meem)',
    arabicRuleName: 'إقلاب (قلب النون ميماً مخفاة)',
    definition: 'قلب النون الساكنة أو التنوين ميماً خالصة لفظاً لا خطاً عند الباء مع مراعاة الغنة حركتين والإخفاء.',
    definitionArabic: 'قلب النون الساكنة أو التنوين ميماً خالصة لفظاً لا خطاً عند الباء مع مراعاة الغنة حركتين والإخفاء.',
    lettersArabic: ['ب'],
    affectedLetters: ['ب'],
    affectedPhonemes: ['n', 'm', 'b'],
    triggeringCondition: {
      description: 'نون ساكنة أو تنوين متبوع بحرف الباء',
      previousContext: [],
      currentContext: ['نْ', 'ً', 'ٍ', 'ٌ'],
      nextContext: ['ب'],
    },
    positionalRequirements: 'يقع في كلمة واحدة (مثل: أَنبِئْهُم) أو في كلمتين (مثل: مِن بَعْدِ)',
    exceptions: ['لا استثناء في رواية حفص'],
    quranicApplicability: 'سائر مواضع النون والتنوين قبل الباء في القرآن الكريم',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام النون الساكنة والتنوين (البيت 14)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'متن تحفة الأطفال وكتب التيسير والشاطبية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: true,
    ghunnahDurationHarakah: 2,
    harakahDuration: {
      minCounts: 2,
      maxCounts: 2,
      standardCounts: 2,
      unitArabic: 'حركتان',
    },
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام النون الساكنة والتنوين',
      verseArabic: 'والثالثُ الإقلابُ عند الباءِ ** ميماً بغنةٍ مع الإخفاءِ',
    },
    pedagogicalTipArabic: 'تلامس الشفتين برفق ولين دون كزّ شديد مع خروج الغنة بمقدار حركتين.',
    commonMistakeArabic: 'الكزّ الشديد على الشفتين وإحداث فرجة مبالغ فيها.',
    isMandatoryInHafs: true,
  },

  'noon_ikhfa_haqiqi': {
    ruleId: 'noon_ikhfa_haqiqi',
    category: TajweedCategory.NOON_SAKINAH_TANWEEN,
    arabicName: 'إخفاء حقيقي',
    englishName: 'Ikhfa Haqiqi (Real Concealment)',
    canonicalRuleName: 'Ikhfa Haqiqi (Real Concealment)',
    arabicRuleName: 'إخفاء حقيقي',
    definition: 'النطق بالنون الساكنة أو التنوين بحالة بين الإظهار والإدغام عارية عن التشديد مع بقاء الغنة حركتين.',
    definitionArabic: 'النطق بالنون الساكنة أو التنوين بحالة بين الإظهار والإدغام عارية عن التشديد مع بقاء الغنة حركتين.',
    lettersArabic: ['ص', 'ذ', 'ث', 'ك', 'ج', 'ش', 'ق', 'س', 'د', 'ط', 'ز', 'ف', 'ت', 'ض', 'ظ'],
    affectedLetters: ['ص', 'ذ', 'ث', 'ك', 'ج', 'ش', 'ق', 'س', 'د', 'ط', 'ز', 'ف', 'ت', 'ض', 'ظ'],
    affectedPhonemes: ['n', 'sˁ', 'ð', 'θ', 'k', 'dʒ', 'ʃ', 'q', 's', 'd', 'tˁ', 'z', 'f', 't', 'dˁ', 'ðˁ'],
    triggeringCondition: {
      description: 'نون ساكنة أو تنوين متبوع بأحد حروف الإخفاء الخمسة عشر (صف ذا ثنا كم جاد شخص قد سما دم طيبا زد في تقى ضع ظالما)',
      previousContext: [],
      currentContext: ['نْ', 'ً', 'ٍ', 'ٌ'],
      nextContext: ['ص', 'ذ', 'ث', 'ك', 'ج', 'ش', 'ق', 'س', 'د', 'ط', 'ز', 'ف', 'ت', 'ض', 'ظ'],
    },
    positionalRequirements: 'يقع في كلمة واحدة (مثل: كُنتُمْ، أَنفُسَكُمْ) أو في كلمتين (مثل: مَن كَانَ، مِن قَبْلُ)',
    exceptions: ['لا استثناء في رواية حفص'],
    quranicApplicability: 'سائر مواضع النون والتنوين قبل الحروف الـ15',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام النون الساكنة والتنوين (الأبيات 15-17)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'متن تحفة الأطفال والشاطبية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: true,
    ghunnahDurationHarakah: 2,
    harakahDuration: {
      minCounts: 2,
      maxCounts: 2,
      standardCounts: 2,
      unitArabic: 'حركتان',
    },
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام النون الساكنة والتنوين',
      verseArabic: 'والرابعُ الإخفاءُ عند الفاضلِ ** من الحروفِ واجبٌ للفاضلِ / في خمسةٍ من بعدِ عشرٍ رمزُها ** في كِلْمِ هذا البيتِ قد ضمّنتُها: صِفْ ذا ثَنا كَمْ جادَ شَخْصٌ قَدْ سَما ** دُمْ طَيِّباً زِدْ في تُقىً ضَعْ ظالِما',
    },
    pedagogicalTipArabic: 'هيئ لسانك عند مخرج الحرف المخفى عنده واجعل الغنة مفخمة إذا كان الحرف مفخماً ومرققة إن كان مرققاً.',
    commonMistakeArabic: 'إلصاق اللسان في مخرج النون كأنه إظهار، أو مدّ الحركة السابقة حتى يتولد منها حرف مد.',
    isMandatoryInHafs: true,
  },

  // 2. أحكام الميم الساكنة
  'meem_ikhfa_shafawi': {
    ruleId: 'meem_ikhfa_shafawi',
    category: TajweedCategory.MEEM_SAKINAH,
    arabicName: 'إخفاء شفوي',
    englishName: 'Ikhfa Shafawi (Labial Concealment)',
    canonicalRuleName: 'Ikhfa Shafawi (Labial Concealment)',
    arabicRuleName: 'إخفاء شفوي',
    definition: 'إخفاء الميم الساكنة عند حرف الباء بغنة حركتين بتلامس لطيف للشفتين دون ضغط زائد.',
    definitionArabic: 'إخفاء الميم الساكنة عند حرف الباء بغنة حركتين بتلامس لطيف للشفتين دون ضغط زائد.',
    lettersArabic: ['ب'],
    affectedLetters: ['ب'],
    affectedPhonemes: ['m', 'b'],
    triggeringCondition: {
      description: 'ميم ساكنة في آخر الكلمة متبوعة بحرف الباء في أول الكلمة التالية',
      previousContext: [],
      currentContext: ['مْ'],
      nextContext: ['ب'],
    },
    positionalRequirements: 'لا يكون إلا من كلمتين (مثل: تَرْمِيهِم بِحِجَارَةٍ، يَعْتَصِم بِاللَّهِ)',
    exceptions: ['لا استثناء في رواية حفص'],
    quranicApplicability: 'سائر مواضع الميم الساكنة قبل الباء',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام الميم الساكنة (البيت 20)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'متن تحفة الأطفال والجزرية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: true,
    ghunnahDurationHarakah: 2,
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام الميم الساكنة',
      verseArabic: 'فالأولُ الإخفاءُ عند الباءِ ** وسَمِّهِ الشفويَّ للقرّاءِ',
    },
    pedagogicalTipArabic: 'تلامس الشفتين بلطف عند الباء مع الغنة حركتين من الخيشوم.',
    commonMistakeArabic: 'الضغط القوي بالأسنان أو تفريج الشفتين تفريجاً واسعاً مشوهاً للصوت.',
    isMandatoryInHafs: true,
  },

  'meem_idgham_shafawi': {
    ruleId: 'meem_idgham_shafawi',
    category: TajweedCategory.MEEM_SAKINAH,
    arabicName: 'إدغام مثلين صغير (إدغام شفوي)',
    englishName: 'Idgham Shafawi (Labial Assimilation)',
    canonicalRuleName: 'Idgham Shafawi (Labial Assimilation)',
    arabicRuleName: 'إدغام مثلين صغير (إدغام شفوي)',
    definition: 'دمج الميم الساكنة في الميم المتحركة بعدها لتصيرا ميماً واحدة مشددة بغنة حركتين.',
    definitionArabic: 'دمج الميم الساكنة في الميم المتحركة بعدها لتصيرا ميماً واحدة مشددة بغنة حركتين.',
    lettersArabic: ['م'],
    affectedLetters: ['م'],
    affectedPhonemes: ['m'],
    triggeringCondition: {
      description: 'ميم ساكنة في آخر الكلمة متبوعة بميم متحركة في أول الكلمة التالية',
      previousContext: [],
      currentContext: ['مْ'],
      nextContext: ['م'],
    },
    positionalRequirements: 'لا يكون إلا من كلمتين (مثل: لَهُم مَّا يَشَاءُونَ)',
    exceptions: ['لا استثناء'],
    quranicApplicability: 'سائر مواضع الميم الساكنة قبل الميم',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام الميم الساكنة (البيت 21)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'تحفة الأطفال وشروحها',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: true,
    ghunnahDurationHarakah: 2,
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام الميم الساكنة',
      verseArabic: 'والثانِ إدغامٌ بمثلِها أتى ** وسَمِّ إدغاماً صغيراً يا فتى',
    },
    pedagogicalTipArabic: 'انطق ميماً مشددة تامة واحبس الصوت بالغنة حركتين كاملتين.',
    commonMistakeArabic: 'قصر زمن الغنة عن حركتين.',
    isMandatoryInHafs: true,
  },

  'meem_izhar_shafawi': {
    ruleId: 'meem_izhar_shafawi',
    category: TajweedCategory.MEEM_SAKINAH,
    arabicName: 'إظهار شفوي',
    englishName: 'Izhar Shafawi (Labial Manifestation)',
    canonicalRuleName: 'Izhar Shafawi (Labial Manifestation)',
    arabicRuleName: 'إظهار شفوي',
    definition: 'إخراج الميم الساكنة من مخرجها بغير غنة زائدة عند الستة والعشرين حرفاً الباقية، وأشدها عند الواو والفاء.',
    definitionArabic: 'إخراج الميم الساكنة من مخرجها بغير غنة زائدة عند الستة والعشرين حرفاً الباقية، وأشدها عند الواو والفاء.',
    lettersArabic: ['أ', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'ن', 'هـ', 'و', 'ي'],
    affectedLetters: ['أ', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'ن', 'هـ', 'و', 'ي'],
    affectedPhonemes: ['m', 'f', 'w', 't', 'd', 'k', 'l'],
    triggeringCondition: {
      description: 'ميم ساكنة متبوعة بأي حرف غير الباء والميم',
      previousContext: [],
      currentContext: ['مْ'],
      nextContext: ['أ', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'ن', 'هـ', 'و', 'ي'],
    },
    positionalRequirements: 'يقع في كلمة واحدة (مثل: أَنْعَمْتَ، تَمْكُثُ) أو في كلمتين (مثل: عَلَيْهِمْ غَيْرِ، لَمْ يَلِدْ)',
    exceptions: ['تأكيد الإظهار الشديد عند الواو والفاء لاتحاد المخرج وقربه'],
    quranicApplicability: 'سائر مواضع الميم الساكنة عدا الباء والميم',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام الميم الساكنة (الأبيات 22-23)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'تحفة الأطفال والجزرية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام الميم الساكنة',
      verseArabic: 'والثالثُ الإظهارُ في البقِيّهْ ** من أحرُفٍ وسَمِّها شَفَوِيَّهْ / واحذَرْ لدى واوٍ وفا أن تَخْتَفِي ** لقُرْبِها ولاتِّحادِ فاعرِفِ',
    },
    pedagogicalTipArabic: 'احذر خصوصاً من إخفاء الميم عند الواو والفاء لقرب المخرج واتحاده.',
    commonMistakeArabic: 'إخفاء الميم عند الفاء والواو، أو قلقلة الميم الساكنة.',
    isMandatoryInHafs: true,
  },

  // 3. أحكام المدود
  'madd_tabii': {
    ruleId: 'madd_tabii',
    category: TajweedCategory.MADD,
    subType: MaddSubtype.TABII,
    arabicName: 'مد طبيعي (أصلي)',
    englishName: 'Natural Madd (Asli)',
    canonicalRuleName: 'Natural Madd (Asli)',
    arabicRuleName: 'مد طبيعي (أصلي)',
    definition: 'المد الذي لا تقوم ذات حرف المد إلا به، ولا يتوقف على سبب من همز أو سكون، ويمد حركتين.',
    definitionArabic: 'المد الذي لا تقوم ذات حرف المد إلا به، ولا يتوقف على سبب من همز أو سكون، ويمد حركتين.',
    lettersArabic: ['ا', 'و', 'ي'],
    affectedLetters: ['ا', 'و', 'ي'],
    affectedPhonemes: ['aː', 'uː', 'iː'],
    triggeringCondition: {
      description: 'حرف مد (ألف ساكنة بعد فتح، واو ساكنة بعد ضم، ياء ساكنة بعد كسر) ليس بعده همز ولا سكون',
      previousContext: ['َ', 'ُ', 'ِ'],
      currentContext: ['ا', 'و', 'ي', 'ٰ'],
      nextContext: [],
    },
    positionalRequirements: 'في كلمة واحدة وصلاً ووقفاً (مثل: قَالَ، يَقُولُ، قِيلَ)',
    exceptions: ['يسقط وصلاً إذا التقى بساكن بعده لمنع التقاء الساكنين'],
    quranicApplicability: 'سائر أحرف المد غير المقيدة بسبب',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أقسام المد (الأبيات 27-29)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'تحفة الأطفال والجزرية والشاطبية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    harakahDuration: {
      minCounts: 2,
      maxCounts: 2,
      standardCounts: 2,
      unitArabic: 'حركتان',
    },
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أقسام المد',
      verseArabic: 'والمدُّ أصليٌ وفرعيٌّ لهُ ** وسَمِّ أولاً طبيعياً وهو ** ما لا توقفٌ له على سببْ ** ولا بدونه الحروفُ تُجتلبْ',
    },
    pedagogicalTipArabic: 'أعطِ حرف المد حركتين بمقدار قبض الإصبع وبسطه باعتدال دون بتر ودون إفراط.',
    commonMistakeArabic: 'اختلاس زمن المد فينقص عن حركتين، أو مده زيادة عن حده.',
    isMandatoryInHafs: true,
  },

  'madd_muttasil': {
    ruleId: 'madd_muttasil',
    category: TajweedCategory.MADD,
    subType: MaddSubtype.MUTTASIL,
    arabicName: 'مد واجب متصل',
    englishName: 'Obligatory Connected Madd',
    canonicalRuleName: 'Obligatory Connected Madd',
    arabicRuleName: 'مد واجب متصل',
    definition: 'أن يأتي حرف المد وبعده همز في كلمة واحدة، وحكمه الوجوب ويمد 4 أو 5 حركات لحفص.',
    definitionArabic: 'أن يأتي حرف المد وبعده همز في كلمة واحدة، وحكمه الوجوب ويمد 4 أو 5 حركات لحفص.',
    lettersArabic: ['ا', 'و', 'ي'],
    affectedLetters: ['ا', 'و', 'ي'],
    affectedPhonemes: ['aː', 'uː', 'iː', 'ʔ'],
    triggeringCondition: {
      description: 'حرف مد بعده همزة متصلة في نفس الكلمة وعليها علامة المد (~) في المصحف',
      previousContext: [],
      currentContext: ['آ', 'يٓ', 'وٓ', 'ٓ'],
      nextContext: ['ء', 'أ', 'إ', 'ئ', 'ؤ'],
    },
    positionalRequirements: 'في كلمة واحدة حتماً (مثل: جَآءَ، السَّمَآءِ، سُوٓءَ)',
    exceptions: ['يمد 6 حركات عند الوقف إذا كانت همزته متطرفة على وجه العارض'],
    quranicApplicability: 'سائر مواضع الهمز المتصل بحرف المد',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام المد (البيت 32)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'تحفة الأطفال والشاطبية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    harakahDuration: {
      minCounts: 4,
      maxCounts: 5,
      standardCounts: 4,
      unitArabic: 'أربع أو خمس حركات',
    },
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام المد',
      verseArabic: 'فواجبٌ إن جاءَ همزٌ بعدَ مدّ ** في كلمةٍ وذا بمتّصلٍ يُعَدّ',
    },
    pedagogicalTipArabic: 'مُدّ الصوت 4 حركات (توسط) أو 5 حركات بميزان متساوٍ طوال التلاوة.',
    commonMistakeArabic: 'قصره إلى حركتين كالطبيعي، أو الإفراط في تمطيطه فوق 5 حركات.',
    isMandatoryInHafs: true,
  },

  'madd_munfasil': {
    ruleId: 'madd_munfasil',
    category: TajweedCategory.MADD,
    subType: MaddSubtype.MUNFASIL,
    arabicName: 'مد جائز منفصل',
    englishName: 'Permissible Separated Madd',
    canonicalRuleName: 'Permissible Separated Madd',
    arabicRuleName: 'مد جائز منفصل',
    definition: 'أن يكون حرف المد في آخر الكلمة والهمز في أول الكلمة التي تليها، ويمد 4 أو 5 حركات من طريق الشاطبية.',
    definitionArabic: 'أن يكون حرف المد في آخر الكلمة والهمز في أول الكلمة التي تليها، ويمد 4 أو 5 حركات من طريق الشاطبية.',
    lettersArabic: ['ا', 'و', 'ي'],
    affectedLetters: ['ا', 'و', 'ي'],
    affectedPhonemes: ['aː', 'uː', 'iː', 'ʔ'],
    triggeringCondition: {
      description: 'حرف مد في نهاية كلمة تليه همزة في بداية الكلمة التالية',
      previousContext: [],
      currentContext: ['آ', 'يٓ', 'وٓ', 'ٓ'],
      nextContext: ['ء', 'أ', 'إ'],
    },
    positionalRequirements: 'بين كلمتين منفصلتين حكماً أو رسماً (مثل: إِنَّآ أَعْطَيْنَاكَ، يَآ أَيُّهَا)',
    exceptions: ['يسقط المد المنفصل عند الوقف على الكلمة الأولى ويصير مداً طبيعياً'],
    quranicApplicability: 'سائر مواضع الهمز المنفصل عن حرف المد',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام المد (البيت 33)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'الشاطبية وتحفة الأطفال',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    harakahDuration: {
      minCounts: 4,
      maxCounts: 5,
      standardCounts: 4,
      unitArabic: 'أربع أو خمس حركات',
    },
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام المد',
      verseArabic: 'وجائزٌ مدٌّ وقصرٌ إن فُصِلْ ** كلٌّ بكلمةٍ وهذا المنفصلْ',
    },
    pedagogicalTipArabic: 'ساوِ بين المتصل والمنفصل عند القراءة برواية حفص من طريق الشاطبية (التوسط 4 حركات).',
    commonMistakeArabic: 'تفاوت أزمنة المدود المنفصلة في نفس المجلس دون اتساق.',
    isMandatoryInHafs: true,
  },

  'madd_lazim_kalimi_muthaqqal': {
    ruleId: 'madd_lazim_kalimi_muthaqqal',
    category: TajweedCategory.MADD,
    subType: MaddSubtype.LAZIM_KALIMI_MUTHAQQAL,
    arabicName: 'مد لازم كَلِمي مُثقّل',
    englishName: 'Heavy Word Compulsory Madd',
    canonicalRuleName: 'Heavy Word Compulsory Madd',
    arabicRuleName: 'مد لازم كَلِمي مُثقّل',
    definition: 'أن يأتي بعد حرف المد سكون أصلي مشدد في كلمة واحدة، ويمد 6 حركات إشباعاً وجوباً (مثل: الحاقّة، الضالّين).',
    definitionArabic: 'أن يأتي بعد حرف المد سكون أصلي مشدد في كلمة واحدة، ويمد 6 حركات إشباعاً وجوباً (مثل: الحاقّة، الضالّين).',
    lettersArabic: ['ا', 'و', 'ي'],
    affectedLetters: ['ا', 'و', 'ي'],
    affectedPhonemes: ['aː', 'uː', 'iː'],
    triggeringCondition: {
      description: 'حرف مد يليه حرف مشدد (مدغم) في نفس الكلمة',
      previousContext: [],
      currentContext: ['آ', 'يٓ', 'وٓ', 'ٓ'],
      nextContext: ['ّ'],
    },
    positionalRequirements: 'في كلمة واحدة حتماً (مثل: وَلَا ٱلضَّآلِّينَ، الحَآقَّةُ، الصَّآخَّةُ)',
    exceptions: ['لا استثناء في مقداره (6 حركات لجميع القراء)'],
    quranicApplicability: 'سائر مواضع المد اللازم الكلمي المثقل',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أقسام المد اللازم (الأبيات 42-45)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'تحفة الأطفال والجزرية والشاطبية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    harakahDuration: {
      minCounts: 6,
      maxCounts: 6,
      standardCounts: 6,
      unitArabic: 'ست حركات',
    },
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أقسام المد اللازم',
      verseArabic: 'فإن بكلمةٍ سكونٌ اجتمعْ ** معْ حرفِ مدٍّ فهو كِلْميٌّ وقَعْ / كِلاهما مُثَقَّلٌ إنْ أُدْغِما ** مُخَفَّفٌ كُلٌّ إذا لم يُدْغَما',
    },
    pedagogicalTipArabic: 'أشبع المد 6 حركات كاملة، ثم انبر نبرة خفيفة عند الحرف المشدد الموالي لإبراز التشديد.',
    commonMistakeArabic: 'نقصان المد عن 6 حركات، أو عدم إبراز تشديد الحرف التالي.',
    isMandatoryInHafs: true,
  },

  'madd_aridh_lis_sukun': {
    ruleId: 'madd_aridh_lis_sukun',
    category: TajweedCategory.MADD,
    subType: MaddSubtype.ARIDH_LIS_SUKUN,
    arabicName: 'مد عارض للسكون',
    englishName: 'Exposed to Sukun Madd',
    canonicalRuleName: 'Exposed to Sukun Madd',
    arabicRuleName: 'مد عارض للسكون',
    definition: 'أن يقع بعد حرف المد حرف ساكن سكوناً عارضاً لأجل الوقف، ويجوز فيه القصر (2) والتوسط (4) والإشباع (6).',
    definitionArabic: 'أن يقع بعد حرف المد حرف ساكن سكوناً عارضاً لأجل الوقف، ويجوز فيه القصر (2) والتوسط (4) والإشباع (6).',
    lettersArabic: ['ا', 'و', 'ي'],
    affectedLetters: ['ا', 'و', 'ي'],
    affectedPhonemes: ['aː', 'uː', 'iː'],
    triggeringCondition: {
      description: 'حرف مد يليه حرف متحرك يُسكن لأجل الوقف عليه في نهاية الكلمة أو رأس الآية',
      previousContext: [],
      currentContext: ['ا', 'و', 'ي', 'ٰ'],
      nextContext: [],
    },
    positionalRequirements: 'عند الوقف فقط على نهاية الكلمة (مثل: ٱلرَّحِيمِ، ٱلْعَٰلَمِينَ، نَسْتَعِينُ)',
    exceptions: ['إذا وُصل صار مداً طبيعياً حركتين فقط'],
    quranicApplicability: 'سائر أواخر الكلمات والآيات المختومة بحرف مد يليه حرف موقوف عليه',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام المد (البيت 34)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'تحفة الأطفال والشاطبية والجزرية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    harakahDuration: {
      minCounts: 2,
      maxCounts: 6,
      standardCounts: 4,
      unitArabic: 'حركتان أو أربع أو ست حركات',
    },
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام المد',
      verseArabic: 'ومثلُ ذا إن عَرَضَ السكونُ ** وَقْفاً كتعلمونَ نستعينُ',
    },
    pedagogicalTipArabic: 'الزم وجهاً واحداً من الأوجه الثلاثة (القصر 2، التوسط 4، أو الطول 6) في جلستك كلها ليكون النظم متسقاً.',
    commonMistakeArabic: 'الخلط العشوائي بين القصر والإشباع في نفس التلاوة.',
    isMandatoryInHafs: false,
  },

  // 4. أحكام القلقلة
  'qalqalah_sughra': {
    ruleId: 'qalqalah_sughra',
    category: TajweedCategory.QALQALAH,
    subType: QalqalahDegree.SUGHRA,
    arabicName: 'قلقلة صغرى',
    englishName: 'Minor Qalqalah (Sughra)',
    canonicalRuleName: 'Minor Qalqalah (Sughra)',
    arabicRuleName: 'قلقلة صغرى',
    definition: 'اضطراب المخرج عند النطق بحرف من حروف (قطب جد) ساكناً في وسط الكلمة أو وسط الكلام موصولاً.',
    definitionArabic: 'اضطراب المخرج عند النطق بحرف من حروف (قطب جد) ساكناً في وسط الكلمة أو وسط الكلام موصولاً.',
    lettersArabic: ['ق', 'ط', 'ب', 'ج', 'د'],
    affectedLetters: ['ق', 'ط', 'ب', 'ج', 'د'],
    affectedPhonemes: ['q', 'tˁ', 'b', 'dʒ', 'd'],
    triggeringCondition: {
      description: 'حرف من حروف (ق، ط، ب، ج، د) ساكن سكوناً أصلياً في وسط الكلمة أو موصولاً في الكلام',
      previousContext: [],
      currentContext: ['قْ', 'طْ', 'بْ', 'جْ', 'دْ'],
      nextContext: [],
    },
    positionalRequirements: 'في وسط الكلمة (مثل: يَجْعَلْ، يَقْطَعُونَ) أو في آخرها موصولة بما بعدها',
    exceptions: ['إذا وقف على الحرف تحولت القلقلة إلى كبرى'],
    quranicApplicability: 'سائر مواضع حروف قطب جد الساكنة وصلاً',
    sourceReference: 'المقدمة الجزرية لابن الجزري - باب صفات الحروف (الأبيات 16-17)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'المقدمة الجزرية وشروح ابن المصنف وشيخ الإسلام زكريا الأنصاري',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    classicalCitation: {
      poemName: 'المقدمة الجزرية لابن الجزري',
      chapterNameArabic: 'باب صفات الحروف',
      verseArabic: 'قَلْقَلَةٌ قُطْبُ جَدٍّ وَاللِّينُ ** وَاوٌ وَيَاءٌ سَكَنَا وَانْفَتَحَا / وَبَيِّنَنْ مُقَلْقَلاً إِنْ سَكَنَا ** وَإِنْ يَكُنْ فِي الْوَقْفِ كَانَ أَبْيَنَا',
    },
    pedagogicalTipArabic: 'حرّك الحرف بنبرة ارتدادية سريعة طليقة دون أن تشوبه بحركة فتح أو كسر أو ضم.',
    commonMistakeArabic: 'خلط صوت القلقلة بحركة كسر أو فتح، أو السكت عند القلقلة.',
    isMandatoryInHafs: true,
  },

  'qalqalah_kubra': {
    ruleId: 'qalqalah_kubra',
    category: TajweedCategory.QALQALAH,
    subType: QalqalahDegree.KUBRA,
    arabicName: 'قلقلة كبرى',
    englishName: 'Major Qalqalah (Kubra)',
    canonicalRuleName: 'Major Qalqalah (Kubra)',
    arabicRuleName: 'قلقلة كبرى',
    definition: 'قلقلة حرف من حروف (قطب جد) إذا وقع ساكناً في آخر الكلمة موقوفاً عليه وكان غير مشدد (مثل: الفلَقْ، محيطْ).',
    definitionArabic: 'قلقلة حرف من حروف (قطب جد) إذا وقع ساكناً في آخر الكلمة موقوفاً عليه وكان غير مشدد (مثل: الفلَقْ، محيطْ).',
    lettersArabic: ['ق', 'ط', 'ب', 'ج', 'د'],
    affectedLetters: ['ق', 'ط', 'ب', 'ج', 'د'],
    affectedPhonemes: ['q', 'tˁ', 'b', 'dʒ', 'd'],
    triggeringCondition: {
      description: 'حرف من حروف (ق، ط، ب، ج، د) موقوف عليه في آخر الكلمة',
      previousContext: [],
      currentContext: ['ق', 'ط', 'ب', 'ج', 'د'],
      nextContext: [],
    },
    positionalRequirements: 'في آخر الكلمة عند الوقف (مثل: الْفَلَقِ، مُحِيطٌ، أَحَدٌ)',
    exceptions: ['إذا وُصل الحرف سقطت القلقلة الكبرى وصار متحركاً بحركته'],
    quranicApplicability: 'سائر الكلمات المختومة بأحد حروف قطب جد عند الوقف',
    sourceReference: 'المقدمة الجزرية لابن الجزري - باب صفات الحروف (البيت 17)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'المقدمة الجزرية وشروحها',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    classicalCitation: {
      poemName: 'المقدمة الجزرية لابن الجزري',
      chapterNameArabic: 'باب صفات الحروف',
      verseArabic: 'وَبَيِّنَنْ مُقَلْقَلاً إِنْ سَكَنَا ** وَإِنْ يَكُنْ فِي الْوَقْفِ كَانَ أَبْيَنَا',
    },
    pedagogicalTipArabic: 'أظهر القلقلة بوضوح وجلاء عند الوقف مع حبس النفس والصوت ثم إطلاقه ارتدادياً بنقاء.',
    commonMistakeArabic: 'ابتلاع صوت القلقلة أو إلحاق همزة ساكتة بعدها (الفلقء).',
    isMandatoryInHafs: true,
  },

  // 5. أحكام الغنة
  'ghunnah_mushaddadah': {
    ruleId: 'ghunnah_mushaddadah',
    category: TajweedCategory.GHUNNAH,
    arabicName: 'غنة النون والميم المشددتين',
    englishName: 'Ghunnah of Doubled Noon and Meem',
    canonicalRuleName: 'Ghunnah of Doubled Noon and Meem',
    arabicRuleName: 'غنة النون والميم المشددتين',
    definition: 'صوت رخيم يخرج من الخيشوم ملازم للنون والميم المشددتين بمقدار حركتين في الوصل والوقف (مثل: إنّ، عمّ).',
    definitionArabic: 'صوت رخيم يخرج من الخيشوم ملازم للنون والميم المشددتين بمقدار حركتين في الوصل والوقف (مثل: إنّ، عمّ).',
    lettersArabic: ['نّ', 'مّ'],
    affectedLetters: ['نّ', 'مّ'],
    affectedPhonemes: ['n', 'm'],
    triggeringCondition: {
      description: 'نون أو ميم عليها شدة (سواء كانت في وسط الكلمة أو آخرها وصلاً ووقفاً)',
      previousContext: [],
      currentContext: ['نّ', 'مّ'],
      nextContext: [],
    },
    positionalRequirements: 'في أي موضع من الكلمة وصلاً ووقفاً (مثل: إِنَّ، عَمَّ، مِنَ الْجِنَّةِ وَالنَّاسِ)',
    exceptions: ['لا استثناء في وجوب الغنة حركتين وصلاً ووقفاً'],
    quranicApplicability: 'سائر مواضع النون والميم المشددتين في القرآن',
    sourceReference: 'تحفة الأطفال للجمزوري - باب حكم النون والميم المشددتين (البيت 18)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'تحفة الأطفال والجزرية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: true,
    ghunnahDurationHarakah: 2,
    harakahDuration: {
      minCounts: 2,
      maxCounts: 2,
      standardCounts: 2,
      unitArabic: 'حركتان',
    },
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'حكم النون والميم المشددتين',
      verseArabic: 'وغُنَّ نوناً ثم ميماً شُدِّدا ** وسَمِّ كُلاً حرفَ غُنَّةٍ بَدا',
    },
    pedagogicalTipArabic: 'أعطِ النون والميم المشددة غنة حركتين من الخيشوم دون زيادة مفردة أو نقصان.',
    commonMistakeArabic: 'المرور السريع عليها كالنون المخففة، أو الإسراف في طولها لأكثر من حركتين.',
    isMandatoryInHafs: true,
  },

  // 6. أحكام التفخيم والترقيق
  'tafkheem_isti_la': {
    ruleId: 'tafkheem_isti_la',
    category: TajweedCategory.TAFKHEEM_TARQEEQ,
    arabicName: 'تفخيم حروف الاستعلاء',
    englishName: 'Tafkheem of Isti\'la Letters',
    canonicalRuleName: 'Tafkheem of Isti\'la Letters',
    arabicRuleName: 'تفخيم حروف الاستعلاء',
    definition: 'تسمين الحرف وتغليظه في المخرج ليمتلئ الفم بصداه في حروف (خص ضغط قظ)، وأعلاها المفتوح المتبوع بألف.',
    definitionArabic: 'تسمين الحرف وتغليظه في المخرج ليمتلئ الفم بصداه في حروف (خص ضغط قظ)، وأعلاها المفتوح المتبوع بألف.',
    lettersArabic: ['خ', 'ص', 'ض', 'غ', 'ط', 'ق', 'ظ'],
    affectedLetters: ['خ', 'ص', 'ض', 'غ', 'ط', 'ق', 'ظ'],
    affectedPhonemes: ['x', 'sˁ', 'dˁ', 'ɣ', 'tˁ', 'q', 'ðˁ'],
    triggeringCondition: {
      description: 'أي حرف من حروف الاستعلاء السبعة: خ، ص، ض، غ، ط، ق، ظ',
      previousContext: [],
      currentContext: ['خ', 'ص', 'ض', 'غ', 'ط', 'ق', 'ظ'],
      nextContext: [],
    },
    positionalRequirements: 'في جميع أحوالها وحركاتها، وتتفاوت مراتبها بحسب الحركة (المفتوح بعده ألف، المفتوح، المضموم، الساكن، المكسور)',
    exceptions: ['تفخيم نسبي في المكسور من حروف: خ، غ، ق'],
    quranicApplicability: 'سائر مواضع حروف الاستعلاء في القرآن الكريم',
    sourceReference: 'المقدمة الجزرية لابن الجزري - باب التفخيم والترقيق (البيت 37)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'المقدمة الجزرية وشروحها المعتمدة',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    classicalCitation: {
      poemName: 'المقدمة الجزرية لابن الجزري',
      chapterNameArabic: 'باب التفخيم والترقيق',
      verseArabic: 'وَحَرْفَ الاسْتِعْلاَءِ فَخِّمْ وَاخْصُصَا ** الاِطْبَاقَ أَقْوَى نَحْوُ قَالَ وَالْعَصَا',
    },
    pedagogicalTipArabic: 'ارفع أقصى اللسان إلى الحنك الأعلى ليمتلئ الفم بصدى الحرف، ولا سيما حروف الإطباق (ص، ض، ط، ظ).',
    commonMistakeArabic: 'ترقيق الطاء والضاد والقاف لتشبه التاء والدال والكاف.',
    isMandatoryInHafs: true,
  },

  // 7. أحكام اللام الساكنة
  'lam_shamsiyyah': {
    ruleId: 'lam_shamsiyyah',
    category: TajweedCategory.LAM_SAKINAH,
    arabicName: 'لام أل الشمسية (إدغام)',
    englishName: 'Solar Lam (Shamsiyyah Idgham)',
    canonicalRuleName: 'Solar Lam (Shamsiyyah Idgham)',
    arabicRuleName: 'لام أل الشمسية (إدغام)',
    definition: 'إدغام لام التعريف في الحرف الذي يليها إذا كان من الحروف الشمسية الأربعة عشر، فتنطق بالحرف التالي مشدداً.',
    definitionArabic: 'إدغام لام التعريف في الحرف الذي يليها إذا كان من الحروف الشمسية الأربعة عشر، فتنطق بالحرف التالي مشدداً.',
    lettersArabic: ['ط', 'ث', 'ص', 'ر', 'ت', 'ض', 'ذ', 'ن', 'د', 'س', 'ظ', 'ز', 'ش', 'ل'],
    affectedLetters: ['ط', 'ث', 'ص', 'ر', 'ت', 'ض', 'ذ', 'ن', 'د', 'س', 'ظ', 'ز', 'ش', 'ل'],
    affectedPhonemes: ['l', 'tˁ', 'θ', 'sˁ', 'r', 't', 'dˁ', 'ð', 'n', 'd', 's', 'ðˁ', 'z', 'ʃ'],
    triggeringCondition: {
      description: 'لام التعريف (أل) متبوعة بأحد الحروف الشمسية الأربعة عشر (طب ثم صل رحما تفز ضف ذا نعم دع سوء ظن زر شريفا للكرم)',
      previousContext: [],
      currentContext: ['ٱل', 'ال'],
      nextContext: ['ط', 'ث', 'ص', 'ر', 'ت', 'ض', 'ذ', 'ن', 'د', 'س', 'ظ', 'ز', 'ش', 'ل'],
    },
    positionalRequirements: 'في أول الأسماء المعرفة بأل (مثل: ٱلرَّحْمَٰنِ، ٱلرَّحِيمِ، ٱلصِّرَٰطَ، ٱلضَّآلِّينَ)',
    exceptions: ['لا استثناء في لام التعريف الداخلة على هذه الحروف'],
    quranicApplicability: 'سائر الأسماء المعرفة بحروف شمسية',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام لام أل ولام الفعل (الأبيات 35-37)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'تحفة الأطفال والشاطبية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام لام أل ولام الفعل',
      verseArabic: 'لِلامِ أَلْ حَالانِ قَبْلَ الأَحْرُفِ ** أُولاهُما إظْهَارُها فَلْتَعْرِفِ / ثَانِيهِما إِدْغَامُها في أَرْبَعِ ** وَعَشْرَةٍ أَيْضاً وَرَمْزَها فَعِ: طِبْ ثُمَّ صِلْ رَحْماً تَفُزْ ضِفْ ذَا نِعَمْ ** دَعْ سُوءَ ظَنٍّ زُرْ شَرِيفاً لِلْكَرَمْ',
    },
    pedagogicalTipArabic: 'انتقل مباشرة من الهمزة إلى الحرف الشمسي مشدداً دون إظهار أي أثر للام.',
    commonMistakeArabic: 'إظهار اللام مع الحروف الشمسية كقول: الـشمس بدلاً من اشّمس.',
    isMandatoryInHafs: true,
  },

  'lam_qamariyyah': {
    ruleId: 'lam_qamariyyah',
    category: TajweedCategory.LAM_SAKINAH,
    arabicName: 'لام أل القمرية (إظهار)',
    englishName: 'Lunar Lam (Qamariyyah Izhar)',
    canonicalRuleName: 'Lunar Lam (Qamariyyah Izhar)',
    arabicRuleName: 'لام أل القمرية (إظهار)',
    definition: 'إظهار لام التعريف ساكنة واضحة قبل الحروف القمرية الأربعة عشر المجموعة في: (ابغِ حجّك وخف عقيمه).',
    definitionArabic: 'إظهار لام التعريف ساكنة واضحة قبل الحروف القمرية الأربعة عشر المجموعة في: (ابغِ حجّك وخف عقيمه).',
    lettersArabic: ['ء', 'ب', 'غ', 'ح', 'ج', 'ك', 'و', 'خ', 'ف', 'ع', 'ق', 'ي', 'م', 'هـ'],
    affectedLetters: ['ء', 'ب', 'غ', 'ح', 'ج', 'ك', 'و', 'خ', 'ف', 'ع', 'ق', 'ي', 'م', 'هـ'],
    affectedPhonemes: ['l', 'ʔ', 'b', 'ɣ', 'ħ', 'dʒ', 'k', 'w', 'x', 'f', 'ʕ', 'q', 'j', 'm', 'h'],
    triggeringCondition: {
      description: 'لام التعريف (أل) متبوعة بأحد الحروف القمرية الأربعة عشر (ابغ حجك وخف عقيمه)',
      previousContext: [],
      currentContext: ['ٱل', 'ال'],
      nextContext: ['ء', 'أ', 'إ', 'ب', 'غ', 'ح', 'ج', 'ك', 'و', 'خ', 'ف', 'ع', 'ق', 'ي', 'م', 'ه', 'هـ'],
    },
    positionalRequirements: 'في أول الأسماء المعرفة بأل (مثل: ٱلْحَمْدُ، ٱلْعَٰلَمِينَ، ٱلْمَغْضُوبِ)',
    exceptions: ['لا استثناء'],
    quranicApplicability: 'سائر الأسماء المعرفة بحروف قمرية',
    sourceReference: 'تحفة الأطفال للجمزوري - باب أحكام لام أل ولام الفعل (البيت 38)',
    verificationStatus: 'VERIFIED',
    knowledgeBaseVersion: TAJWEED_KB_VERSION,
    evidenceProvenance: 'تحفة الأطفال والجزرية',
    ruleStatus: 'ACTIVE',
    requiresGhunnah: false,
    classicalCitation: {
      poemName: 'تحفة الأطفال للجمزوري',
      chapterNameArabic: 'أحكام لام أل ولام الفعل',
      verseArabic: 'قَبْلَ ارْبَعٍ مَعْ عَشْرَةٍ خُذْ عِلْمَهُ ** مِنِ ابْغِ حَجَّكَ وَخَفْ عَقِيمَهُ',
    },
    pedagogicalTipArabic: 'أظهر اللام ساكنة بنقاء ودون قلقلة أو سكت.',
    commonMistakeArabic: 'قلقلة اللام القمرية أو إدغامها خطأً في الجيم أو الياء.',
    isMandatoryInHafs: true,
  },
};
